Release from staging to master - 2021-03-17
HumanCellAtlas/metadata-schema pull request #1371
Opened 2021-03-17 12:59 UTC by ESapenaVentura

### Release notes

**Versions:**

links.json - v3.0.0
project.json - v14.2.0

**Test metadata**:
UUID - 7b351f00-522f-49a9-8302-754eb076f979
Root folder - infrastructure_testing_files/dcp_metadata_testing_files/7b351f00-522f-49a9-8302-754eb076f979

**Functionality:**

- Fixed javascript validator (Points to correct URL)
- Added fail_test for links.json
- Fixed schema linter (Points to correct URL)
- Fixed pullapprove and updated lists
- Added test data spreadsheet

2021-03-26 12:39 UTC, ruchim requested changes
a) Requesting changes/clarification around DUO changes. b) A few questions about about why certain changes were made  c) a few optional thoughts about reframing descriptions

Looking forward to re-reviewing!

2021-03-26 12:39 UTC, ruchim commented on docs/jsonBrowser/module.md
> +data_normalization_methods | Method(s) used to normalize data in the matrix | array | no |  | Data normalization method(s) |  |
I'd love to see a list of allowed "type"s in the docs. It will help our validation, plus it will make it clear to the consumers of this standard for what's appropriate!

2021-03-26 12:39 UTC, ruchim commented on docs/jsonBrowser/module.md
> +## Data use ontology<a name='Data use ontology'></a>
hmm so I think earlier we said we'd remove it, so this feels counter to that decision?

2021-03-26 12:39 UTC, ruchim commented on json_schema/core/file/file_core.json
> +            "description": "Has the file come from a contributor or the DCP?",
(optional) Alternat description: The name of the entity that generated the file

2021-03-26 12:39 UTC, ruchim commented on json_schema/module/ontology/data_use_ontology.json
> +{
I don't believe this file should be included!

2021-03-26 12:39 UTC, ruchim commented on json_schema/module/protocol/matrix.json
> +            "description": "How is the data derived?",
given the items, it seems the derivation process is more like "type of computational tool used in generating the matrix object"

2021-03-26 12:39 UTC, ruchim commented on json_schema/module/protocol/matrix.json
> +                "enum": [
question:so is this field a list of enums or a single enum. Meaning can items = ["alignment", "quantification"] or it has to be items = "alignment"

2021-03-26 12:39 UTC, ruchim commented on json_schema/property_migrations.json
> +            "property": "data_use_restrictions",
I'd love a description of what this enables? data use restrictions feels a bit like arbitrary terminology and if we're removing DUO codes, not sure this is necessary

2021-03-26 12:39 UTC, ruchim commented on json_schema/type/project/project.json
> +            "description": "A list of European Genome phenome Archive dataset or study accessions.",
this is a list because 1 HCA project = many EGA studies?

2021-03-26 12:39 UTC, ruchim commented on json_schema/type/project/project.json
> +            "description": "A list of European Genome phenome Archive dataset or study accessions.",
sorry, you probably mentioned this but just verifying to be absolutely sure

2021-03-26 12:39 UTC, ruchim commented on tests/schema_test_files/system/test_fail_links.json
> +{
given the name of the file -- is this a test data to show a bad links json? can we add a comment to describe what causes it to fail?

2021-03-26 12:54 UTC, ESapenaVentura commented on docs/jsonBrowser/module.md
> +## Data use ontology<a name='Data use ontology'></a>
We decided to keep the module but there is no field in the schema that loads it, so it's effectively inexistent! (Can't be used in a project)

We took this decision to avoid some work in the future re-creating the module, but we can discuss if we need to delete it completely

2021-03-26 12:55 UTC, ESapenaVentura commented on json_schema/module/protocol/matrix.json
> +                "enum": [
it's a list of enums, meaning that e.g. "alignment" and "quantification" can be both specified for the same protocol

2021-03-26 12:55 UTC, ESapenaVentura commented on json_schema/type/project/project.json
> +            "description": "A list of European Genome phenome Archive dataset or study accessions.",
Yep! there may be cases where 1 HCA project == Many EGA accessions

2021-03-26 14:12 UTC, ruchim commented on docs/jsonBrowser/module.md
> +## Data use ontology<a name='Data use ontology'></a>
if you're worried about recreating the code, maybe it can just be put in a separate branch? @hannes-ucsc does that feel right to you too?

2021-03-29 09:17 UTC, ESapenaVentura commented on json_schema/property_migrations.json
> +            "property": "data_use_restrictions",
This is necessary for an automated migration tool, this will be used (Still not operational) to try and automate migrations to the best of our extents.

This just states that from project 14 (last major update, recorded down in the document) to 15, the field was deleted. (Basically, if someone was to update from 14.3.0 to 15.0.0, they need to delete the field to make the instance valid)

Of course, this has been a rollback so technically it has never been used and no project entity will need this specific update, but I think it's best practice to keep a record of this anyways!

2021-03-29 09:32 UTC, ESapenaVentura commented on docs/jsonBrowser/module.md
> +data_normalization_methods | Method(s) used to normalize data in the matrix | array | no |  | Data normalization method(s) |  |
I agree, this is usually the case but thanks to this comment I have observed there's a bug where enum arrays won't be loaded properly. I'm opening a ticket to investigate into this issue!

2021-03-29 10:42 UTC, ESapenaVentura commented on docs/jsonBrowser/module.md
> +data_normalization_methods | Method(s) used to normalize data in the matrix | array | no |  | Data normalization method(s) |  |
Fixed it in this PR https://github.com/HumanCellAtlas/metadata-schema/pull/1379/files since it's a webhook it actually also fixed this doc :)

2021-03-29 10:55 UTC, ESapenaVentura commented on json_schema/core/file/file_core.json
> +            "description": "Has the file come from a contributor or the DCP?",
I think that may be a little confusing to some users (e.g. people may understand that field as the institution they are working in), but happy to discuss about it

2021-03-29 22:48 UTC, hannes-ucsc requested changes
The data use stuff needs to go.

Off-topic: 

Reviewing this PR is made more difficult by the cruft contained therein. The documentation markup is automatically generated so ideally it wouldn't be part of the history. I don't really understand why an artifact that can be generated *from* the source, needs to be part *of* the source. The history in the PR is incomprehensible. No reviewer is gonna go though 114 commits.

I'm fine with letting these cruft issues slide the first time but it is not sustainable in the long run. Any ideas of how this could be improved?

2021-03-29 22:48 UTC, hannes-ucsc commented on json_schema/core/file/file_core.json
> +            "description": "Has the file come from a contributor or the DCP?",
The term entity is already taken.

The phrasing is a bit awkward but more importantly, I'd avoid repeating the enum values in the description. We'd have to rewrite it every time a new file source needs to be added.

```suggestion
            "description": "The source of the file. This is typically an organisation, person or dedicated process.",
```

2021-03-29 22:48 UTC, hannes-ucsc commented on json_schema/module/ontology/data_use_ontology.json
> +{
Correct. As agreed on 3/24.

2021-03-29 22:48 UTC, hannes-ucsc commented on json_schema/module/protocol/matrix.json
> +                "enum": [
Is there not an existing ontology we can utilize? Part of the reason we're doing this whole thing is to rely on EBI's ontology validation.

2021-03-29 22:48 UTC, hannes-ucsc commented on json_schema/property_migrations.json
> +            "property": "data_use_restrictions",
No data use related changes should be in this PR. Not even rollback migrations of features already released. This needs to be removed.

2021-03-29 22:48 UTC, hannes-ucsc commented on json_schema/type/file/analysis_file.json
> +            "description": "Number of cells analyzed in the matrix.",
Not all analysis files are matrices. The description should clarify that this property only applies to the latter.

2021-03-29 22:48 UTC, hannes-ucsc commented on json_schema/type/project/project.json
> +            "description": "A list of European Genome phenome Archive dataset or study accessions.",
Capitalization and phrasing is odd.
```suggestion
            "description": "A list of accessions referring to EGA (European Genome-Phenome Archive) datasets or studies.",
```

2021-03-29 22:48 UTC, hannes-ucsc commented on json_schema/module/protocol/matrix.json
> +                "CPM (counts per million)",
```suggestion
                    "CPM (counts per million)",
```

2021-03-29 22:48 UTC, hannes-ucsc commented on json_schema/module/protocol/matrix.json
> +                "enum": [
Same question, is there no existing ontology we could use?

2021-03-29 22:48 UTC, hannes-ucsc commented on json_schema/module/protocol/matrix.json
> +            "guidelines": "Should be one of: CPM (counts per million), TPM (transcripts per kilobase million), RPKM(reads per kilobase of exon per million reads mapped), FPKM (fragments per kilobase
Did you write this by hand? If so why can't this be generated automatically? (I assume this is predominantly meant for people filling out spreadsheets),

2021-03-29 22:48 UTC, hannes-ucsc commented on json_schema/module/protocol/matrix.json
> +    "properties": {
Which of these properties would you expect to be exposed in the Data Browser?

2021-03-29 22:48 UTC, hannes-ucsc commented on json_schema/module/protocol/matrix.json
> +    "description": "Information relating to generation of count matrices",
Sure this is only for count matrices? What about GEX matrices?

2021-03-29 22:48 UTC, hannes-ucsc commented on json_schema/system/links.json
> +                    "enum": [
I'm assuming this is an unrelated bug fix?

2021-03-29 22:48 UTC, hannes-ucsc commented on json_schema/versions.json
>  {
What's the purpose of this file? Neither TDR nor Azul rely on it.

2021-03-30 04:36 UTC, mshadbolt commented on json_schema/versions.json
>  {
It is used by the scripts within this repo to increment version numbers when we run the 'release_prepare.py' script. The following lines in the 'version_update.py' reads this json file to get current versions then writes the updated `versions.json` with the updated versions of any schemas or dependent schemas, that have been incremented by the major/minor/patch release. (https://github.com/HumanCellAtlas/metadata-schema/blob/ff27788edc635f6e631a64b3fcda63f54fc6fe7b/src/version_update.py#L25, https://github.com/HumanCellAtlas/metadata-schema/blob/ff27788edc635f6e631a64b3fcda63f54fc6fe7b/src/version_update.py#L64). 

I believe it is also used by our [metadata schema publisher](https://github.com/HumanCellAtlas/metadata-schema-publisher) that publishes the versioned schemas to their url addresses.

2021-03-30 04:53 UTC, mshadbolt commented on tests/schema_test_files/system/test_fail_links.json
> +{
I am not sure I feel that comfortable adding comments to json files (though I realise this might be controversial). There are a set of basic tests including json validation and some pass/fail tests that are run by Travis each time a PR is made (or run manually as we make changes). In the output from these tests, one can see the reason why a fail test fails: https://travis-ci.com/github/HumanCellAtlas/metadata-schema/jobs/494698958#L400

2021-03-30 05:00 UTC, mshadbolt commented on json_schema/system/links.json
> +                    "enum": [
This was a change you had requested. We thought since we had already merged it and it has zero impact it would be okay to include in this release. https://github.com/HumanCellAtlas/metadata-schema/issues/1333

2021-03-30 09:31 UTC, Wkt8 commented on docs/jsonBrowser/module.md
> +## Data use ontology<a name='Data use ontology'></a>
We will remove this from the PR.

2021-03-30 09:40 UTC, Wkt8 commented on json_schema/module/protocol/matrix.json
> +                "enum": [
There is not an existing ontology at the moment. However, we think there is still value added from this field to data consumers, even if it is not ontologised.

2021-03-30 09:41 UTC, Wkt8 commented on json_schema/module/ontology/data_use_ontology.json
> +{
We will remove it from the PR.

2021-03-30 09:51 UTC, Wkt8 commented on json_schema/module/protocol/matrix.json
> +                "enum": [
Same answer, there is not one now but we think this field still adds enough value without one.

2021-03-30 09:53 UTC, Wkt8 commented on json_schema/module/protocol/matrix.json
> +            "description": "How is the data derived?",
That sounds like a sensible change we can make to the description field. We will do it.

2021-03-30 09:53 UTC, Wkt8 commented on json_schema/type/file/analysis_file.json
> +            "description": "Number of cells analyzed in the matrix.",
That is correct. Will make this change.

2021-03-30 09:54 UTC, Wkt8 commented on json_schema/module/protocol/matrix.json
> +    "description": "Information relating to generation of count matrices",
Good catch. We'll make this change and make it the more general 'matrices'.

2021-03-30 10:29 UTC, mshadbolt commented
Just so the reviewers who have reviewed so far are aware (@hannes-ucsc @ruchim). We have taken your feedback on board and we are now preparing a new feature branch to merge into staging with your suggested fixes. We are also removing all traces of the data_use_ontology_module and rolling back the project versioning and re-releasing the schemas so that it was like the module and the version of the project schema that referred to it never existed. We will also re-generate the test data. Once this is all completed we will re-request review. Thanks for all your feedback.

2021-03-30 10:50 UTC, mshadbolt commented on json_schema/module/protocol/matrix.json
> +            "guidelines": "Should be one of: CPM (counts per million), TPM (transcripts per kilobase million), RPKM(reads per kilobase of exon per million reads mapped), FPKM (fragments per kilobase
I made an assessment that the time it would take me to figure out how to generate this automatically would be longer than doing a quick manual hack to replace characters and reformat into a sentence. Thanks for catching the mistake that I made. Yes it is displayed in the spreadsheet so that users can see what options they are allowed to use for the field.

2021-03-30 15:04 UTC, kbergin commented on json_schema/type/protocol/analysis/analysis_protocol.json
> +        },
Is this a required field?

2021-03-30 15:06 UTC, kbergin reviewed
Had a question about the analysis_protocol json changes. Outside of that question, everything else shouldn't impact analysis as far as I can tell.

2021-03-30 22:23 UTC, hannes-ucsc commented on json_schema/module/protocol/matrix.json
> +            "guidelines": "Should be one of: CPM (counts per million), TPM (transcripts per kilobase million), RPKM(reads per kilobase of exon per million reads mapped), FPKM (fragments per kilobase
I didn't catch any mistakes. I just noticed that it's a bad idea to manually maintain this field if it can be generated automatically from the enum values. It's not fair to compare the effort one manual fix to that of an automatic implementation, if that implementation eliminates the need to maintain the duplication for *every* enum in the schema, and *every* time an enum is modified. At some point the automatic implementation effort will amortize. I won't hold up the PR for this reason. It's a minor annoyance to the reviewers because it increases the amount of text to review.

2021-03-30 22:34 UTC, hannes-ucsc commented on json_schema/module/protocol/matrix.json
> +                "enum": [
Let's continue this discussion here: https://github.com/HumanCellAtlas/dcp2/pull/8#discussion_r604326828

2021-03-31 00:19 UTC, hannes-ucsc commented on json_schema/versions.json
>  {
Got it. Thank you for the explanation.

2021-03-31 00:30 UTC, hannes-ucsc commented on json_schema/system/links.json
> +                    "enum": [
I don't think this is zero impact. If there is a typo or omission in this enum, it could cause future exports to fail to import into TDR.

When you say "we had already merged it" do you mean merged into develop and staging? If so, that statement applies to all changes in this PR, correct?

Are there any staging areas in the wild containing `links.json` documents that use this schema?

I'm just trying to evaluate the risks that lumping this unrelated change in would create.

2021-03-31 00:32 UTC, hannes-ucsc commented on json_schema/type/protocol/analysis/analysis_protocol.json
> +        },
No. See the `required` property in line 5 of this file.

2021-03-31 00:54 UTC, hannes-ucsc requested changes
A few more comments.

2021-03-31 00:54 UTC, hannes-ucsc commented on json_schema/type/file/analysis_file.json
> +        "matrix_cell_count": {
@kbergin, do you plan to support this field in the `analysis_file` instances created by your workflows?

2021-03-31 00:54 UTC, hannes-ucsc commented on json_schema/type/protocol/analysis/analysis_protocol.json
> +        },
Do you plan to support any of the properties added by the matrix module in the `analysis_protocol` instances created by your workflows?

2021-03-31 00:54 UTC, hannes-ucsc commented on json_schema/core/file/file_core.json
> +            ],
```suggestion
            "enum":[
                "DCP/2 Analysis",
                "Contributor",
                "Array Express",
                "GEO",
                "SCEA",
                "SCP",
                "DCP/1 Matrix Service",
                "LungMAP",
                "Zenodo",
                "Publication",
            ],
```

to be consistent with the set of sources that we currently track (https://github.com/DataBiosphere/azul/blob/6b45e0e30fbe90c7b3944ee691c95328c7883ab2/src/azul/plugins/metadata/hca/transform.py#L271).

It would be undesirable to be less informative than the current "hacky" mechanism.

2021-03-31 01:38 UTC, hannes-ucsc commented on json_schema/core/file/file_core.json
> +            ],
Might also want to add `"HCA Release"`

2021-03-31 04:29 UTC, mshadbolt commented on json_schema/system/links.json
> +                    "enum": [
I think one of the aims of having all components review a change to the schema is to catch any typos or omissions. So while we have put our best effort into capturing all the values for these fields accurately in the enum, and reviewed it internally, I would hope that the components that rely on these fields would also check to see that we haven't omitted or misspelled anything.

If you prefer us to remove this change let us know. Could you also let us know what we should do to enable a future merge of this change to be successful. Is the concern around previous versions of `links.json` not being compatible with the new version if they don't follow the provided enum?

2021-03-31 17:25 UTC, hannes-ucsc commented on json_schema/system/links.json
> +                    "enum": [
No other components rely on this enum. It's just that TDR performs schema validation so if a `links.json` generated bi Ingest comes along with a legitimate `protocol_type` that fails to validate against this enum because the enum contains a mistake, the import would fail. I don't know if we should separate this change out or not until my questions above are answered.

2021-03-31 17:46 UTC, hannes-ucsc commented on json_schema/system/links.json
> +                    "enum": [
Let me also clarify my question

> Are there any staging areas in the wild containing links.json documents that use this schema?

Has this schema version (with the added enum) been used to validate any existing, real-world `links.json` documents?

2021-04-05 19:27 UTC, NoopDog commented on json_schema/core/file/file_core.json
> +            ],
@hannes-ucsc it might be nice to also represent if a file source type is "internal" or "external". We could do this by making this an enum of dictionaries instead of strings, with an added property called "type". This would be of use in simplifying to users the distinction between DCP and CGM matrices.

2021-04-05 19:51 UTC, NoopDog reviewed
Hi there, I would like to propose an alternative to making an optional field for matrix_cell_count on analysis_file.json.

Another way to do this is to make a matrix_file.json that includes analysis_file.json, basically extending it and making a new type, and then adding matrix_cell_count as a required field to matrix_file.json.  

We already have image_file, reference_file, sequence_file and it seems to me that since matrix files are one of our primary outputs, that we would do well to model them explicitly.

This would provide a location to attach other matrix-related properties in the future and allow the schema to specify how to validate them, and also enable filtering by the file type.

2021-04-06 16:41 UTC, hannes-ucsc commented on json_schema/module/protocol/matrix.json
> +            "guidelines": "Should be one of: CPM (counts per million), TPM (transcripts per kilobase million), RPKM(reads per kilobase of exon per million reads mapped), FPKM (fragments per kilobase
I will a separate create issue for this. It was meant as a suggestion. I should have made that more clear.

2021-04-06 20:16 UTC, kbergin commented on json_schema/type/file/analysis_file.json
> +        "matrix_cell_count": {
We can add it to our backlog to take advantage of this field. But I'm not sure how to backpopulate it to previously analyzed datasets..

2021-04-06 20:17 UTC, kbergin commented on json_schema/type/protocol/analysis/analysis_protocol.json
> +        },
I didn't have plans to do so, but if there are downstream features it would enable we can consider it. Would this be for both project matrices and individual matrices?

2021-04-07 04:11 UTC, mshadbolt commented on json_schema/system/links.json
> +                    "enum": [
As this schema has not been released, no existing `links.json` documents are at this version so I don't know how they could be validated against this new version. The test data should be the only jsons that should be at, and therefore validated, against this proposed version. Does the importer validate against the latest schema versions, or the version that is contained within each json document? 
One thing that could have happened would be if a project has been exported from staging using this version for testing purposes, since these schema updates were released in staging. I am not sure whether or not this has occurred. Nothing in production should have `links.json` documents at this new proposed version.

2021-04-07 04:21 UTC, mshadbolt commented on json_schema/core/file/file_core.json
> +            ],
I did some searching but I can't find anything about having an enum of objects in json schema. Or are you suggesting an additional field in the schema? If it is a 'nice to have' would it be possible to make a ticket on the repo with your proposal and we will prioritise it. Thanks!

2021-04-07 10:35 UTC, mshadbolt commented on json_schema/core/file/file_core.json
> +            ],
@hannes-ucsc I have incorporated the enums as requested in the PR I am making with all feedback from the review process (https://github.com/HumanCellAtlas/metadata-schema/pull/1381). We'll wait until test data has been reviewed and all expected changes are made in this branch before internal review, then squash and merge to minimise commits, then re-publish the schemas on staging.

2021-04-07 10:39 UTC, mshadbolt commented on json_schema/property_migrations.json
> +            "property": "data_use_restrictions",
we have removed this and rolled back the version of project in the inprogress feedback PR https://github.com/HumanCellAtlas/metadata-schema/pull/1381

2021-04-08 08:32 UTC, Wkt8 commented on json_schema/module/protocol/matrix.json
> +    "properties": {
This shouldn't hold up the release - but we expect that the two fields should be included in the metadata .tsv file on the browser, and eventually the data_normalization and field would be able to be filtered by data consumers in the browser.

2021-04-13 20:14 UTC, hannes-ucsc requested changes

2021-04-13 20:14 UTC, hannes-ucsc commented on json_schema/type/protocol/analysis/analysis_protocol.json
> +        },
I think both, unless that's prohibitively difficult to implement. I've opened https://github.com/HumanCellAtlas/dcp2/issues/12 to track this separately.

2021-04-13 20:14 UTC, hannes-ucsc commented on tests/schema_test_files/system/test_fail_links.json
> +  "describedBy": "https://schema.dev.data.humancellatlas.org/system/9.9.9/links.json",
This URL does not point at a schema file. Is that intended?

2021-04-13 20:16 UTC, hannes-ucsc commented on json_schema/module/protocol/matrix.json
> +                "enum": [
https://github.com/HumanCellAtlas/metadata-schema/pull/1371#discussion_r612724811

2021-04-22 19:53 UTC, danielsotirhos commented on json_schema/core/file/file_core.json
> +        "file_source": {
Please add `ENA` to the list of enum values.
This request based on the addition of the new value in the upcoming batch of [contributor generated matrices](https://docs.google.com/spreadsheets/d/1m9tXswoNAEYJDVlCKqc9L6p0c7hbOwddkQxdqxXydqY/edit?ts=601bb5db#gid=0)

2021-04-29 14:10 UTC, hannes-ucsc requested changes

2021-04-29 14:10 UTC, hannes-ucsc commented on json_schema/module/protocol/matrix.json
> +            "items":{
```suggestion
            "items": {
```

2021-04-29 14:10 UTC, hannes-ucsc commented on tests/schema_test_files/system/test_fail_links.json
> +  "describedBy": "https://schema.dev.data.humancellatlas.org/system/9.9.9/links.json",
```
$ curl 'https://schema.dev.data.humancellatlas.org/system/9.9.9/links.json'
<!DOCTYPE html>
<html>
<head>
    <title>HCA Metadata Schemas</title>
</head>
<body>
<h1>HCA Metadata Schemas</h1>
<div id="listing"></div>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">
  var S3BL_IGNORE_PATH = false;
  var EXCLUDE_FILE = 'index.html';
</script>
<script type="text/javascript" src="https://rawgit.com/rufuspollock/s3-bucket-listing/gh-pages/list.js"></script>
</body>
```

2021-04-29 14:10 UTC, hannes-ucsc commented on tests/schema_test_files/system/test_fail_links.json
> +
```suggestion
```

2021-04-29 14:10 UTC, hannes-ucsc commented on json_schema/core/file/file_core.json
> +        "file_source": {
I second that. Daniel is acting as my proxy here.

2021-04-29 15:38 UTC, hannes-ucsc commented on json_schema/core/file/file_core.json
> +        "file_source": {
@clairerye: "The reference of ENA in the spreadsheet was a mistake. Spreadsheet will be corrected."

2021-04-29 15:38 UTC, kbergin commented on json_schema/type/protocol/analysis/analysis_protocol.json
> +        },
Ok we can investigate more in that issue. Thanks!

2021-04-29 15:38 UTC, kbergin approved these changes

2021-04-29 15:41 UTC, hannes-ucsc commented on json_schema/module/protocol/matrix.json
> +            "items":{
Not a deal-breaker. @clairerye: "Will be fixed before merged". I will post formatting configuration for Amnon.

2021-04-29 15:49 UTC, hannes-ucsc commented on tests/schema_test_files/system/test_fail_links.json
> +  "describedBy": "https://schema.dev.data.humancellatlas.org/system/9.9.9/links.json",
Since this is a failure test, the URL doesn't matter.

2021-04-29 15:50 UTC, hannes-ucsc commented on tests/schema_test_files/system/test_fail_links.json
> +
See formatting fixes above.

2021-04-29 15:51 UTC, hannes-ucsc approved these changes

2021-04-29 15:51 UTC, ruchim approved these changes
all good

2021-04-30 12:53 UTC, aherbst-broad approved these changes

2021-04-30 17:33 UTC, NoopDog approved these changes

2021-05-05 12:04 UTC, merged