Reviewed with new guidelines for commiting changes.
HumanCellAtlas/metadata-schema pull request #1392
Opened 2021-06-02 14:20 UTC by ESapenaVentura

### Release notes

For `docs/commiters.md`:
- Added pre-requisites
- Updated obsolete information about commiting process

### Reviews requested

- Need wranglers to review as this is an SOP change

2021-08-03 13:47 UTC, ESapenaVentura commented
Tagging @amnonkhen and @Wkt8 as reviewers

2021-08-04 08:57 UTC, amnonkhen commented on docs/committers.md
>          git checkout -b mf-new-mouse-module-Issue222
```suggestion
        git checkout -b mf-new-mouse-module-dcp-222
```

2021-08-04 08:57 UTC, amnonkhen commented on docs/committers.md
> +1. **Make** and **switch** to a new working branch from staging. Name the branch following the convention: `initials-brief-desc-of-branch-scope`. Optionally, you can tag a GitHub issue (e.g. `Issue22
```suggestion
1. **Make** and **switch** to a new working branch from staging. Name the branch following the convention: `initials-brief-desc-of-branch-scope`. Optionally, you can tag a GitHub issue (e.g. `dcp-222`) in the branch name.
```

2021-08-04 09:04 UTC, amnonkhen requested changes
Generally OK. A few minor comments.

2021-08-23 13:22 UTC, ESapenaVentura commented on docs/committers.md
> +1. **Make** and **switch** to a new working branch from staging. Name the branch following the convention: `initials-brief-desc-of-branch-scope`. Optionally, you can tag a GitHub issue (e.g. `Issue22
Why this change? Is `Issue` as a preffix not clear?

2021-08-23 13:58 UTC, Wkt8 commented on docs/release_process.md
Would add here some steps for changing the spreadsheet template located in the geo_to_hca folder. 

1. In the [geo_to_hca ](https://github.com/ebi-ait/geo_to_hca/tree/master/docs) repo, download the latest version of the hca_template, and edit to add the new metadata schema changes. 
2. Move the now outdated template to the [outdated templates](https://github.com/ebi-ait/geo_to_hca/tree/master/docs/Outdated%20Templates) folder, and upload the new up-to-date template following DDMMYYhca_template.xlsx to the repo. 
3. Notify the other wranglers to download the new version of the spreadsheet template.

2021-08-25 15:41 UTC, ESapenaVentura commented on docs/release_process.md
>          git push origin develop
```suggestion
        git push origin staging
```

2021-09-08 10:41 UTC, ESapenaVentura commented on docs/committers.md
> +1. **Make** and **switch** to a new working branch from staging. Name the branch following the convention: `initials-brief-desc-of-branch-scope`. Optionally, you can tag a GitHub issue (e.g. `Issue22
@amnonkhen

2021-09-16 08:14 UTC, merged