Added HCA publication status to publications module. Fixes #1345
HumanCellAtlas/metadata-schema pull request #1396
Opened 2021-07-07 13:41 UTC by ESapenaVentura

### Release notes

For `module/project/publication` schema:
- Added non-required field `hca_publication_status` #1345

2021-07-07 13:56 UTC, ESapenaVentura commented
**Note**: I have left the field as non-required for now, there was a strong feeling to make it required but I think we didn't have enough time to discuss at the meeting.

2021-07-07 14:17 UTC, ruchim requested changes
I would love one question answered before approval. 

How is this publication information meant to be used in the HCA data browser? If we can add this in the description of the PR -- it may simplify future reviews.

2021-07-07 14:17 UTC, ruchim commented on json_schema/module/project/publication.json
> +        "is_hca_publication": {
is it likely/possible that a project has more than 1 publication?

2021-07-07 14:21 UTC, ESapenaVentura commented on json_schema/module/project/publication.json
> +        "is_hca_publication": {
Yes, it is possible, although if I have to go by gut intuition, not very likely. This module gets loaded in 

https://github.com/HumanCellAtlas/metadata-schema/blob/c1e477d50f64c65339fa1f8c83b29aff2a753aed/json_schema/type/project/project.json#L61-L67

as an array, so multiple publications is possible. I can't remember if there is currently any case in the DCP but we have recorded instances of the same project in more than one publication in our backoffice.

2021-07-07 14:30 UTC, ESapenaVentura commented
> I would love one question answered before approval.
> 
> How is this publication information meant to be used in the HCA data browser? If we can add this in the description of the PR -- it may simplify future reviews.

Noted - I'll try to be more clear about end goals in the future!

For this scenario, this flag may be used to highlight the official HCA publications (Selected by the HCA scientific committee) in the browser. Currently we have no way of highlighting these, and they are supposed to be of high impact to the scientific goal of the HCA. @clairerye may have a little more information on how we would like this to be displayed.

2021-07-07 15:31 UTC, aherbst-broad reviewed
Left a few questions.

2021-07-07 15:31 UTC, aherbst-broad commented on docs/jsonBrowser/module.md
> +is_hca_publication | Has the publication been accepted as an official HCA publication, acording to the process described in https://www.humancellatlas.org/publications/ ? | boolean | no |  | HCA Publ
Typo: 
```suggestion
is_hca_publication | Has the publication been accepted as an official HCA publication, according to the process described in https://www.humancellatlas.org/publications/ ? | boolean | no |  | HCA Publication? |  | yes; no
```

2021-07-07 15:31 UTC, aherbst-broad commented on json_schema/module/project/publication.json
> +            "example": "yes; no"
I believe boolean properties can only be one of `true` or `false`

2021-07-07 15:31 UTC, aherbst-broad commented on json_schema/module/project/publication.json
> +            "description": "Has the publication been accepted as an official HCA publication, acording to the process described in https://www.humancellatlas.org/publications/ ?",
Typo:
```suggestion
            "description": "Has the publication been accepted as an official HCA publication, according to the process described in https://www.humancellatlas.org/publications/ ?",
```

2021-07-07 18:48 UTC, ruchim commented on json_schema/module/project/publication.json
> +        "is_hca_publication": {
awesome -- so there's two different things happening here -- one which is the property name implies the response is true/false (has_*) and then we want an array list to consume hca publications. I might propose that we just call this property "hca_publication" (so the boolean assumption no longer applies) and then the array can be 0 or n elements

2021-07-07 18:50 UTC, ruchim commented
> > I would love one question answered before approval.
> > How is this publication information meant to be used in the HCA data browser? If we can add this in the description of the PR -- it may simplify future reviews.
> 
> Noted - I'll try to be more clear about end goals in the future!
> 
> For this scenario, this flag may be used to highlight the official HCA publications (Selected by the HCA scientific committee) in the browser. Currently we have no way of highlighting these, and they are supposed to be of high impact to the scientific goal of the HCA. @clairerye may have a little more information on how we would like this to be displayed.

Got it -- so we are thinking this means on a project page -- we can better highlight official HCA publications. Is there a need to be able to "filter" by whether a project has HCA publications or not? or whether we expect HCA publications information as something that can be exported/downloaded when doing a faceted search?

2021-07-08 02:26 UTC, kbergin approved these changes
I second Ruchi's comment about the term implying it's boolean when it may actually be an array of publications. But none of these things will impact analysis so I'm approving from the analysis perspective.

2021-07-08 03:20 UTC, hannes-ucsc requested changes
I don't feel strongly about my comments below but I want to know what the reason is for not making this required. Generally speaking, it is better to be strict first and relax the requirements later if needed than to start lenient and later trying to tighten the requirements. The former is a backwards compatible update, the latter isn't and requires schema migration.

2021-07-08 03:20 UTC, hannes-ucsc commented on json_schema/module/project/publication.json
> +        "is_hca_publication": {
The name is a bit awkward. "publication" is implied by the context. There is no precedent for an "is_" prefix in the name of other boolean properties:

https://github.com/HumanCellAtlas/metadata-schema/search?l=JSON&q=boolean

Can I throw 

```suggestion
        "part_of_hca": {
```

in the ring? This is based on the wording on https://www.humancellatlas.org/publications/

2021-07-08 03:20 UTC, hannes-ucsc commented on json_schema/module/project/publication.json
> +        "is_hca_publication": {
Alternatively, we could model this more richly by making this an enum that tracks the review process:

```
"hca_review": {
    "type": "string",
    "enum": [ "pending", "rejected", "accepted" ]
```

2021-07-08 10:48 UTC, ESapenaVentura commented on json_schema/module/project/publication.json
> +            "example": "yes; no"
Yes, you are right, but we currently gather the metadata from contributors in a spreadsheet. To avoid confusion for non-programmatic users, the spreadsheet importer automatically transforms "yes" and "no" into the boolean value. We have other instances of this in the schema: 
https://github.com/HumanCellAtlas/metadata-schema/blob/c1e477d50f64c65339fa1f8c83b29aff2a753aed/json_schema/module/project/contact.json#L70-L75

We display the example in the spreadsheet as help text on top to guide on what the answer should look like, so it's very useful for the contributor!

2021-07-08 10:49 UTC, ESapenaVentura commented on json_schema/module/project/publication.json
> +            "description": "Has the publication been accepted as an official HCA publication, acording to the process described in https://www.humancellatlas.org/publications/ ?",
Good catch!

2021-07-08 13:22 UTC, ESapenaVentura commented on json_schema/module/project/publication.json
> +        "is_hca_publication": {
>I think there's a misunderstanding here. This schema describes a single publication. The project schema has a property that is a list of documents that match this schema. Any number of the project's publications can be an official HCA publication. I think this is modeled correctly.

Yes, spot on! The field itself is not an array, but the property in the `project` type schema that loads the module is.

About the name of the field, I've been discussing with the team, and `part_of_hca` does not sound less confusing to some members, as some members pointed out everything we ingest will be part of HCA, even if it's not an official hca publication. How about we drop the `is` for an `official`? (`official_hca_publication`?)

I understand there is a concern about redundancy, but that's how they are officially named, hca publications. Happy to jump on a call to discuss further about this!

2021-07-08 13:22 UTC, ESapenaVentura commented on json_schema/module/project/publication.json
> +        "is_hca_publication": {
>Alternatively, we could model this more richly by making this an enum that tracks the review process:
>.
>.


About the last comment, I like the idea to make the model more rich, but I think it will make the process very complicated. We usually only have access to the final decision if it's positive, so getting (and updating over time when it changes!) the status may make it a bit complicated.

2021-07-08 13:24 UTC, ESapenaVentura commented
> I don't feel strongly about my comments below but I want to know what the reason is for not making this required. Generally speaking, it is better to be strict first and relax the requirements later if needed than to start lenient and later trying to tighten the requirements. The former is a backwards compatible update, the latter isn't and requires schema migration.

Agree. I don't think it will cause significant overhead (It's not a piece of metadata that is hard to get), so making it required and relaxing the requirements later if needed sounds good to me. I will apply the change!

2021-07-08 17:52 UTC, NoopDog commented on json_schema/module/project/publication.json
> +        "is_hca_publication": {
@ESapenaVentura Yes`official_hca_publication` seems fine. Also would be great to make this required if possible. 

I presume that making this field optional for now makes it possible to do a simpler data migration and mark the official HCA papers only. Is this correct? Or is it about the same effort to then mark all non HCA publications "false" in the same go? 

My preference would be to make it required now if it does not create an undue burden on the data ops to backfill. 

My understanding (and correct me if I am wrong) is that the metadata is "Open world" meaning that the absence of a fact does not imply the fact is false, but only that it is unknown by the system.

2021-07-09 13:03 UTC, aherbst-broad approved these changes

2021-07-09 13:34 UTC, ESapenaVentura commented on json_schema/module/project/publication.json
> +        "is_hca_publication": {
Perfect, thanks! `official_hca_publication` it is then!

>I presume that making this field optional for now makes it possible to do a simpler data migration and mark the official HCA papers only. Is this correct? Or is it about the same effort to then mark all non HCA publications "false" in the same go?

Whenever we do a data migration, we do have (in the tracking spreadsheet) a field to indicate papers that have been accepted as HCA publications, so (even if it's not super thorough) we may already have something to mark papers as hca publications!

>My preference would be to make it required now if it does not create an undue burden on the data ops to backfill.

I changed it yesterday, it is required now! I think the biggest burden will be how to "massively" migrate the project json, but I think we have the tools and it's just a matter of having someone on the team work on it.

>My understanding (and correct me if I am wrong) is that the metadata is "Open world" meaning that the absence of a fact does not imply the fact is false, but only that it is unknown by the system.

💯  spot on!

2021-07-09 15:04 UTC, ESapenaVentura commented
> > > I would love one question answered before approval.
> > > How is this publication information meant to be used in the HCA data browser? If we can add this in the description of the PR -- it may simplify future reviews.
> > 
> > 
> > Noted - I'll try to be more clear about end goals in the future!
> > For this scenario, this flag may be used to highlight the official HCA publications (Selected by the HCA scientific committee) in the browser. Currently we have no way of highlighting these, and they are supposed to be of high impact to the scientific goal of the HCA. @clairerye may have a little more information on how we would like this to be displayed.
> 
> Got it -- so we are thinking this means on a project page -- we can better highlight official HCA publications. Is there a need to be able to "filter" by whether a project has HCA publications or not? or whether we expect HCA publications information as something that can be exported/downloaded when doing a faceted search?

I think, at least as a start, it would be good to display that information at the level of the project page. From there, we can work out if we need to provide with those 2 features you mention - Being able to filter projects by HCA publications and exporting/downloading publication info from those HCA publications!

2021-07-09 17:23 UTC, NoopDog commented on json_schema/module/project/publication.json
> +        "is_hca_publication"
```suggestion
        "official_hca_publication"
```

2021-07-09 17:25 UTC, NoopDog commented on json_schema/module/project/publication.json
> +            "user_friendly": "Official HCA Publication?",
```suggestion
            "user_friendly": "Official HCA Publication",
```

2021-07-09 17:28 UTC, NoopDog commented on json_schema/module/project/publication.json
> +            "example": "yes; no"
Hi @ESapenaVentura it seems to me the documentation should describe the metadata and how it will appear in the json, not how it will appear in the ingest spreadsheet. Is there a way the spreadsheet display can apply the correct transform rather than using "yes, no" here?`

2021-07-09 17:34 UTC, NoopDog requested changes
I made two suggestions below to fix the name of `official_hca_publication` in the required list, to remove the "?" from the friendly name and I also left a comment about using "yes" "no" instead of "true" "false" for the example values of the `boolean` field.  I feel the documentation should document the metadata and the json, and not be concerned with the input spreadsheet.

2021-07-15 10:22 UTC, ESapenaVentura commented on json_schema/module/project/publication.json
> +            "user_friendly": "Official HCA Publication?",
Thanks for the suggestion! Being a boolean property, I'd prefer to keep the question mark in the user friendly field, is there any issue with that?

2021-07-15 19:56 UTC, hannes-ucsc commented on json_schema/module/project/publication.json
> +            "user_friendly": "Official HCA Publication?",
No.

2021-07-15 20:03 UTC, hannes-ucsc requested changes
One show-stopping issue.

2021-07-15 20:03 UTC, hannes-ucsc commented on json_schema/module/project/publication.json
> +            "example": "yes; no"
The fact that some schema properties in this repository are taylored towards spreadsheet generation is a separate issue that we're not going to fix in this PR.

2021-07-15 20:07 UTC, hannes-ucsc commented
> > I would love one question answered before approval.
> > How is this publication information meant to be used in the HCA data browser? If we can add this in the description of the PR -- it may simplify future reviews.
> 
> Noted - I'll try to be more clear about end goals in the future!
> 
> For this scenario, this flag may be used to highlight the official HCA publications (Selected by the HCA scientific committee) in the browser. Currently we have no way of highlighting these, and they are supposed to be of high impact to the scientific goal of the HCA. @clairerye may have a little more information on how we would like this to be displayed.

If this property is to be rendered in the Data Browser, Azul needs to index it and we would like a corresponding PR against the schema test data repo that adds this property there so we can write unit tests.

2021-07-16 12:20 UTC, clairerye commented
> > > I would love one question answered before approval.
> > > How is this publication information meant to be used in the HCA data browser? If we can add this in the description of the PR -- it may simplify future reviews.
> > 
> > 
> > Noted - I'll try to be more clear about end goals in the future!
> > For this scenario, this flag may be used to highlight the official HCA publications (Selected by the HCA scientific committee) in the browser. Currently we have no way of highlighting these, and they are supposed to be of high impact to the scientific goal of the HCA. @clairerye may have a little more information on how we would like this to be displayed.
> 
> If this property is to be rendered in the Data Browser, Azul needs to index it and we would like a corresponding PR against the schema test data repo that adds this property there so we can write unit tests.

Yes please to it being rendered in the data browser. When this PR is merged we can create the test data and will let you know when that is available. Once this PR is approved, are you happy for us to merge staging to master or do you want to sign off on the test data first and therefore the staging to master PR too? Also happy to confirm this in the post demo session on Tuesday (I have put it on the agenda).

2021-07-16 16:11 UTC, hannes-ucsc commented
As with PR [1388](https://github.com/HumanCellAtlas/metadata-schema/pull/1388#issuecomment-881558737), no master PR necessary, I would say.

2021-07-19 15:44 UTC, amnonkhen commented on json_schema/module/project/publication.json
> +        "is_hca_publication"
Leaving `?` in.

2021-07-19 15:45 UTC, amnonkhen commented on json_schema/module/project/publication.json
> +        "is_hca_publication"
Resolving on behalf of @ESapenaVentura who is on vacation.

2021-07-19 15:45 UTC, amnonkhen commented on json_schema/module/project/publication.json
> +            "user_friendly": "Official HCA Publication?",
Resolving on behalf of @ESapenaVentura who is on vacation.

2021-07-19 16:25 UTC, amnonkhen approved these changes

2021-07-20 04:02 UTC, NoopDog commented on json_schema/module/project/publication.json
> +            "user_friendly": "Official HCA Publication?",
Hi @ESapenaVentura @hannes-ucsc this is the friendly name a property. Usually, property names do not contain punction. We use this friendly name in the metadata dictionary in the data portal for example and plan to eventually use it in the data browser table column names.

Also, currently in the metadata schema, it seems that other friendly names for boolean properties do not contain punctuation. See `contact.corresponding_contributor` or `death.cold_perfused` or `death.normothermic_regional_perfusion` for examples.

2021-07-21 08:04 UTC, clairerye commented on json_schema/module/project/publication.json
> +            "user_friendly": "Official HCA Publication?",
I see your point @NoopDog, lets wait until Enrique is back to resolve this. I think we all agree we want to be as consistent as possible, so I am thinking Enrique has something quite specific in mind here.

2021-07-21 21:46 UTC, hannes-ucsc commented on json_schema/module/project/publication.json
> +            "user_friendly": "Official HCA Publication?",
Precedent seems to be not to have question mark:

https://github.com/HumanCellAtlas/metadata-schema/search?q=%22type+boolean%22

2021-07-21 21:48 UTC, hannes-ucsc commented
If we want to follow the yet-to-be accepted SOP, reviews should be requested from all reviewers after changes have been pushed.

2021-07-22 15:33 UTC, amnonkhen commented on json_schema/module/project/publication.json
> +            "user_friendly": "Official HCA Publication?",
Personally, I prefer to avoid the question mark. 

From reading the comments I understood that @ESapenaVentura wants the question mark 


> Thanks for the suggestion! Being a boolean property, I'd prefer to keep the question mark in the user friendly field, is there any issue with that?

and @hannes-ucsc being ok with that.

> No.

Here's a screen shot:

![image](https://user-images.githubusercontent.com/927145/126666381-fdc0ff4c-939a-4e52-b9da-e8609cc68a6e.png)

Have I misunderstood?

2021-07-22 16:32 UTC, hannes-ucsc commented on json_schema/module/project/publication.json
> +            "user_friendly": "Official HCA Publication?",
I don't have an issue with the question mark because I don't think it's a big deal. I pointed out that precedence seems to be not to have a question mark in the `user_friendly` on boolean properties. Those two statements don't contradict each other

2021-07-22 18:11 UTC, ruchim approved these changes
boolean confusion cleared -- thanks!

2021-07-26 09:26 UTC, amnonkhen commented on json_schema/module/project/publication.json
> +            "user_friendly": "Official HCA Publication?",
After discussion the question mark with @ESapenaVentura, we decided to get rid of it.

2021-07-29 18:27 UTC, NoopDog approved these changes
Nice. Thank you!

2021-08-02 16:39 UTC, hannes-ucsc approved these changes

2021-08-13 13:52 UTC, merged