Removed channel and probe from required fields in imaging_protocol. Fixes #1430
HumanCellAtlas/metadata-schema pull request #1431
Opened 2021-11-24 07:01 UTC by willrockout

### Release notes

For `imaging_protocol.json` schema:
- Removed `channel` and `probe` from the required field list.
 

### Reviews requested

- Need 2 Reviewers to approve because this is a minor update
- Last Reviewer to review/approve, merge changes

2021-12-06 18:10 UTC, theathorn approved these changes

2021-12-09 17:16 UTC, gabsie commented
Hey, everyone, can we possibly get these reviews in, possibly by Monday next week? @aherbst-broad , @amnonkhen @hannes-ucsc , @khajoue2 , @kishorikonwar , @NoopDog , @ruchim ?

Thank you!

2021-12-17 00:43 UTC, ruchim approved these changes
Looks good! This question doesn’t bar any changes — tho if someone can do a quick explanation of why these are no longer required/ what’s the new info we learned in #dcp-2, that would be appreciated!

2021-12-17 00:48 UTC, hannes-ucsc approved these changes

2021-12-17 13:28 UTC, ESapenaVentura approved these changes
LGTM 👍

2021-12-17 13:28 UTC, ESapenaVentura requested changes
Actually I just realised it's missing the update_log.csv file

2021-12-17 16:40 UTC, NoopDog approved these changes

2021-12-20 14:53 UTC, aherbst-broad approved these changes

2021-12-20 15:07 UTC, ESapenaVentura commented on json_schema/update_log.csv
> +type/protocol/imaging/imaging_protocol.json,minor,"Removed channel and probe from required fields. #Fixes 1420",,
```suggestion
type/protocol/imaging/imaging_protocol,minor,"Removed channel and probe from required fields. #Fixes 1420",,
```

2021-12-20 16:44 UTC, ESapenaVentura approved these changes

2021-12-20 16:45 UTC, merged