Added anchors to ega_accession and dbgap_accession patterns. Fixes #1425
HumanCellAtlas/metadata-schema pull request #1436
Opened 2021-12-06 02:44 UTC by willrockout

### Release notes

For <project.json> schema:
- Added anchors to <ega_accessions> and <dbgap_accessions>
 

### Reviews requested

- Need 2 Reviewers to approve because this is a <minor> update
- Last Reviewer to review/approve, merge changes by <deadline>

2021-12-06 18:11 UTC, theathorn approved these changes

2021-12-07 16:20 UTC, NoopDog approved these changes

2021-12-17 00:46 UTC, ruchim reviewed
Quick question — if one HCA project is associated with 2 Dbgap or 2 EGA studies —but they only have only been approved to access one of the multiple studies — that’s complexity for the custodian to manage and to decide whether someone should get access?

2021-12-17 00:49 UTC, hannes-ucsc approved these changes

2021-12-17 01:04 UTC, hannes-ucsc approved these changes

2021-12-17 13:27 UTC, ESapenaVentura requested changes
I put a suggestion on the change type. I think we need to review the docs on the patch changes.

This is not a patch change by any mean, as it breaks backwards compatibility with previous instances

(e.g. this is addressing an issue with a field that was filled with 2 ega accessions in a string, that won't be accepted as valid with the new version thus breaking compatibility) https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/evolution.md#schema-versioning

2021-12-17 13:27 UTC, ESapenaVentura commented on json_schema/update_log.csv
> +type/project/project.json,patch,"Added anchors to ega_accessions and dbgap_accessions. Fixes #1425",,
```suggestion
type/project/project,major,"Added anchors to ega_accessions and dbgap_accessions. Fixes #1425",,
```

2021-12-17 15:19 UTC, ruchim approved these changes
looks good to me! lets just talk through implications of this for managed access datasets in a future session

2021-12-20 16:40 UTC, ESapenaVentura approved these changes

2021-12-20 16:40 UTC, merged