Allow inclusion of an external DRS URI in file descriptors
HumanCellAtlas/metadata-schema pull request #1437
Opened 2021-12-09 16:02 UTC by aherbst-broad

Draft PR related to this DCP system spec [update](https://github.com/HumanCellAtlas/dcp2/pull/55).

2021-12-09 16:03 UTC, aherbst-broad commented on json_schema/system/file_descriptor.json
> +    {"required": ["content_type", "size",  "sha256", "crc32c"]}
This section is intended to express a mutually exclusive condition, i.e., if a `drs_uri` is present, `content_type`, `size`, `sha256`, `crc32c` should _not_ be present (and vice-versa).

2022-02-15 12:41 UTC, JoshuaFortriede commented on json_schema/system/file_descriptor.json
> +    {"required": ["content_type", "size",  "sha256", "crc32c"]}
For a mutually exclusive condition, the "oneOf" keyword should be used. With that said, I am not sure these field lists should be mutually exclusive. I can imagine implementation layers that would want the content type, size, and hashes of a file while also utilizing a drs_uri to serve the file. For instance, a data shopping cart where you can check boxes to add files to your shopping cart, and you are summing the file size to inform the user of their total end payload.

2022-02-15 12:42 UTC, JoshuaFortriede commented
For a mutually exclusive condition, the "oneOf" keyword should be used. With that said, I am not sure these field lists should be mutually exclusive. I can imagine implementation layers that would want the content type, size, and hashes of a file while also utilizing a drs_uri to serve the file. For instance, a data shopping cart where you can check boxes to add files to your shopping cart, and you are summing the file size to inform the user of their total end payload.

2022-02-17 17:49 UTC, hannes-ucsc requested changes
~Tag~

2022-03-21 13:15 UTC, aherbst-broad commented
@JoshuaFortriede I believe the array notation is equivalent to `anyOf` (both enforce an `or` condition). See the example here https://cswr.github.io/JsonSchema/spec/multiple_types/

2022-03-21 13:18 UTC, aherbst-broad commented
@JoshuaFortriede does your comment still hold? The current rev of this PR is not using an `anyOf` condition for the required properties and instead has reverted to the original set of required properties.

2022-03-22 18:33 UTC, ESapenaVentura requested changes
Given the description of the field, we are only expecting a single value at a time (or the absence of the field) and therefore I don't think we need the "oneOf" keyword:
https://json-schema.org/understanding-json-schema/reference/type.html

The schema change itself looks good to me, but all the PRs must go through staging first as stated in the [commiters document](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/committers.md#specific-how-to-for-making-changes)

2022-03-22 19:00 UTC, hannes-ucsc commented
@ESapenaVentura, we wanted to make sure that people don't accidentally create phantom files by omitting the property. That's why the PR distinguishes between absence and `null` value.

2022-03-23 06:15 UTC, NoopDog commented on json_schema/system/file_descriptor.json
> -      "pattern" : "^https?://schema.(.*)?humancellatlas.org/system/(([0-9]{1,}.[0-9]{1,}.[0-9]{1,})|([a-zA-Z]*?))/file_descriptor$"
Curious why `pattern` is being deleted here.

2022-03-23 12:51 UTC, aherbst-broad commented on json_schema/system/file_descriptor.json
> -      "pattern" : "^https?://schema.(.*)?humancellatlas.org/system/(([0-9]{1,}.[0-9]{1,}.[0-9]{1,})|([a-zA-Z]*?))/file_descriptor$"
@NoopDog good catch, that was removed to allow the lungmap folks to test and develop while this schema change was in flight. It has been restored.

2022-03-23 13:03 UTC, aherbst-broad commented
@ESapenaVentura apologies for not following the SOP, I've rebased against the staging branch according to the committers doc.

2022-03-24 16:45 UTC, hannes-ucsc requested changes
Conflicts.

2022-03-28 17:30 UTC, hannes-ucsc approved these changes

2022-03-28 17:30 UTC, hannes-ucsc commented on changelog.md
> +
Don't know why this change is here. It seems unrelated but I don't have sufficient insight into the release process use in this repository.

2024-09-07 06:13 UTC, hannes-ucsc commented
Continued in https://github.com/HumanCellAtlas/metadata-schema/pull/1575

2024-09-07 06:13 UTC, closed without merging