Added treatment protocol to schema - issue1428
HumanCellAtlas/metadata-schema pull request #1446
Opened 2022-02-11 12:10 UTC by ami-day

Added treatment protocol to schema

1. Include "Fixes #<issue number>" in the PR title.
2. Include summary of each change, grouped by schema, under "Release notes".
3. Indicate how many Reviewers are requested to approve PR before merging, why, and when the PR should be merged. -->

### Release notes

Added a new treatment protocol.
 
### Reviews requested

- Need at least 3 Reviewers including from AIT/UCSC/Data Browser team to approve because this is a major update.
- Last Reviewer to review/approve, merge changes by 16/02/2022

2022-02-14 17:58 UTC, hannes-ucsc commented on json_schema/type/protocol/biomaterial_collection/treatment_protocol.json
> +            "comment": "Consider making this an ontology in the future.",
Why don't you do this now? Ontologizing properties in retroactively is a major effort, especially if the string values found in the wild aren't consistent with the ontology.

2022-02-14 18:21 UTC, aherbst-broad approved these changes

2022-02-21 13:55 UTC, ESapenaVentura commented on json_schema/type/protocol/biomaterial_collection/treatment_protocol.json
> +            "comment": "Consider making this an ontology in the future.",
+1 to hannes, let's not leave to the future what we can do now just because we don't allocate capacity to research what terms could be used

2022-02-21 18:11 UTC, ami-day commented on json_schema/type/protocol/biomaterial_collection/treatment_protocol.json
> +            "comment": "Consider making this an ontology in the future.",
Thanks for the feedback. I had left this comment after copying from an alternative json file, as I am actually not sure that we should require an ontology term for treatment method in particular.

An example could be: **T cell activation** (http://www.ebi.ac.uk/efo/EFO_0030037), which is a child of **assay** (http://purl.obolibrary.org/obo/OBI_0000070). I don't see many other treatment method examples however under assay or under the **experimental process** term (http://www.ebi.ac.uk/efo/EFO_0002694). What do you think? we could bring this up on Friday when we have a regular catch-up with the UCSC wranglers to make a decision.

2022-03-22 16:05 UTC, kbergin approved these changes

2022-03-28 12:32 UTC, ami-day commented on json_schema/type/protocol/biomaterial_collection/treatment_protocol.json
> +            "comment": "Consider making this an ontology in the future.",
I have added the new ontology.

2022-04-05 09:08 UTC, ami-day commented
Hi @hannes-ucsc I have addressed the review comments and added an ontology to the treatment protocol schema, and made some other small updates to the pull request.

2022-04-05 15:49 UTC, hannes-ucsc approved these changes

2022-04-19 08:57 UTC, amnonkhen commented on json_schema/versions.json
> +                    "treatment_protocol": "0.0.0"
@ami-day Is `0.0.0` the correct value?

2022-04-19 13:01 UTC, ami-day commented on json_schema/versions.json
> +                    "treatment_protocol": "0.0.0"
OH! no, it should be 0.0.1

2022-04-19 13:06 UTC, ami-day reviewed
Updated the treatment protocol schema version

2022-04-19 13:07 UTC, ami-day commented
Hi @hannes-ucsc @kbergin @aherbst-broad I have updated the ontology information and treatment protocol version. Is this pull request good to go? any other recommended changes? Thanks.

2022-04-19 16:40 UTC, hannes-ucsc approved these changes

2022-04-19 16:45 UTC, hannes-ucsc commented
Some people don't get email notifications for GitHub activity. That's why the SOP includes weekly pings on Slack. The SOP also mandates that authors re-request reviews (here on GH, using the sidebar on the right) after they make changes, even from reviewers that have already approved.

2022-04-22 15:26 UTC, hannes-ucsc approved these changes

2022-04-28 02:32 UTC, NoopDog approved these changes

2022-04-28 12:56 UTC, aherbst-broad approved these changes

2022-04-28 15:46 UTC, amnonkhen approved these changes

2022-05-09 08:59 UTC, ESapenaVentura requested changes

2022-05-26 15:02 UTC, ami-day commented on json_schema/type/protocol/biomaterial_collection/treatment_protocol.json
> +            "example": "insulin signalling pathway; immune cell activation; chemokine signalling pathway."
Yes, I think this is a good idea!

2022-05-26 15:22 UTC, ami-day commented on json_schema/type/protocol/biomaterial_collection/treatment_protocol.json
> +            "example": "insulin signalling pathway; immune cell activation; chemokine signalling pathway."
Done.

2022-06-07 12:20 UTC, ESapenaVentura requested changes
Couple of minor comments/corrections, other than that LGTM!

Please remember that we need to add GO to HCAO and ensure that everything under `OBI:0000070` is in HCAO as well

2022-06-07 12:20 UTC, ESapenaVentura commented on json_schema/update_log.csv
> +module/ontology/target_pathway_ontology,major,"Added Treatment protocol target pathway ontology. Fixes #1428",,
Could you be a bit more specific with the change messages for each entity?

2022-06-07 14:36 UTC, kbergin approved these changes

2022-06-09 18:13 UTC, ami-day commented on json_schema/update_log.csv
> +module/ontology/target_pathway_ontology,major,"Added Treatment protocol target pathway ontology. Fixes #1428",,
done

2022-06-10 08:38 UTC, ami-day commented
Waiting to import the relevant ontology to HCAO before approving the pull request, will create a ticket in the ontology repo.

2022-06-24 14:55 UTC, hannes-ucsc approved these changes

2022-06-24 14:55 UTC, hannes-ucsc commented on json_schema/versions.json
> +                    "treatment_protocol": "0.0.0"
Just noting that it wasn't actually changed to `0.0.1`

2022-07-18 13:41 UTC, ami-day commented on json_schema/versions.json
> +                    "treatment_protocol": "0.0.0"
Sorry to get back so late on this, 0.0.0 is actually the correct value so I will leave it as it is

2022-07-18 13:46 UTC, ami-day commented
> Couple of minor comments/corrections, other than that LGTM!
> 
> Please remember that we need to add GO to HCAO and ensure that everything under `OBI:0000070` is in HCAO as well

Zoe is working on this!

2022-07-18 13:52 UTC, ami-day commented
Hi @hannes-ucsc, the version is actually correct (0.0.0) so I will leave it as it is, and have re-requested review. Thanks for your feedback!

2022-07-18 18:20 UTC, hannes-ucsc approved these changes
Updated list of reviewers to reflect the [recently updated list](https://github.com/HumanCellAtlas/dcp2/commit/2a3cfb1bb1efbe6b6c4ff73e8bcad100c91f928d) in the SOP.

2022-08-01 09:57 UTC, merged