Added permeabilisation time field with time units. Fixes #1471
HumanCellAtlas/metadata-schema pull request #1473
Opened 2022-07-06 11:02 UTC by ESapenaVentura

### Release notes

For `type/protocol/imaging/imaging_preparation_protocol.json` schema:
- Added non-required field `permeabilisation_time`
- Added non-required field `permeabilisation_time_unit`
- Added dependency between permeabilisation_time and permeabilisation_time_unit
 

### Reviews requested

- This is a minor update
- Reviews are requested as per usual

### Rationale
Based on the findings by the education team, exposed in the [May 24th demos](https://docs.google.com/presentation/d/10-Ei7SXCqyrLLlWyAGWxS0E02bG6r-sIAumyHBtDoIo/edit#slide=id.g12e39c13645_1_0), we have decided to add the "permeabilisation time" field to the imaging_preparation_protocol to ensure we are capturing the information needed to represent Visium experiments

see #1471

2022-07-06 15:35 UTC, ncalvanese1 approved these changes
Looks good to me!

2022-07-06 18:35 UTC, NoopDog approved these changes

2022-07-06 21:51 UTC, hannes-ucsc requested changes

2022-07-06 21:51 UTC, hannes-ucsc commented on docs/jsonBrowser/type.md
> +permeabilisation_time_unit | The unit in which Permeabilisation time is expressed. | object | no | [See module  time_unit_ontology](module.md/#time_unit_ontology) | Permeabilisation time unit |  |
```suggestion
permeabilisation_time_unit | The unit in which permeabilisation time is expressed. | object | no | [See module  time_unit_ontology](module.md/#time_unit_ontology) | Permeabilisation time unit |  | 
```

2022-07-06 21:51 UTC, hannes-ucsc commented on json_schema/type/protocol/imaging/imaging_preparation_protocol.json
> +    },
`dependentRequired` was [introduced](https://json-schema.org/draft/2019-09/release-notes.html#validation-vocabulary) in release 2019-09 of JSONSchema while all schemas in this repository consistently use draft 7. At best, this constraint would be ignored by the validators currently used, in the worst case it would break validation of otherwise valid documents. I don't actually know what happens. Have you tested this with a draft 7 validator?

Aside from that, it might be mode elegant to represent "measured values" (values with a unit), as nested `object`s with two required properties. That way you get to reuse measured values as, I think, what your team calls modules.

2022-07-12 15:08 UTC, ESapenaVentura commented on json_schema/type/protocol/imaging/imaging_preparation_protocol.json
> +    },
Apologies, I didn't realise it was introduced in draft 09. You are right, at least for now we are not prepared for that!

I like your solution, but i think it needs some discussion (I am thinking, for example, how to avoid the case in which a time-related field would be filled with weight units)

I have created a ticket to keep this in our backlog/discuss [here](https://github.com/HumanCellAtlas/metadata-schema/issues/1479), and for now I will resort to our usual implementation (Which is the same as it is now, but without the `dependentRequired` keyword)

2022-07-12 15:12 UTC, ESapenaVentura commented on docs/jsonBrowser/type.md
> +permeabilisation_time_unit | The unit in which Permeabilisation time is expressed. | object | no | [See module  time_unit_ontology](module.md/#time_unit_ontology) | Permeabilisation time unit |  |
Corrected!

2022-07-12 17:03 UTC, hannes-ucsc approved these changes

2022-07-25 13:57 UTC, idazucchi commented on json_schema/type/protocol/imaging/imaging_preparation_protocol.json
> +    },
For draft 2019-09 `dependentRequired` substitutes in part `dependencies` from draft 7. We could use `dependencies` where Enrique initially proposed to use `dependentRequired`. 
It would be the same draft as the rest of the schema, it would be validated by the validators and it's the built-in mechanism to indicate dependencies between different parts of the schema.

2022-08-01 16:49 UTC, hannes-ucsc commented on json_schema/type/protocol/imaging/imaging_preparation_protocol.json
> +    },
Works for me.

2022-08-04 15:25 UTC, ESapenaVentura commented
Applied the `dependencies` keyword as discussed above - Please review!

2022-08-04 15:36 UTC, ncalvanese1 approved these changes
Looks good to me!

2022-08-05 16:44 UTC, NoopDog approved these changes

2022-08-15 11:02 UTC, amnonkhen approved these changes

2022-08-18 23:11 UTC, hannes-ucsc approved these changes

2022-08-19 14:00 UTC, merged