Added value to enum for file source. Fixes #1487.
HumanCellAtlas/metadata-schema pull request #1490
Opened 2022-09-09 14:41 UTC by ESapenaVentura

### Release notes

For `file_core` schema:
- Added value to enum for file source
 

### Reviews requested

- This is a minor change to all the schemas it affects (file_core + file type schemas)

2022-09-09 17:36 UTC, hannes-ucsc commented on json_schema/core/file/file_core.json
> +                "HCA Ingest"
Having second thought on this. Should this be

```suggestion
                "DCP/2 Ingest"
```

2022-09-09 17:37 UTC, hannes-ucsc commented on json_schema/core/file/file_core.json
> +                "HCA Ingest"
… considering the existing `DCP/1 Matrix Service`, that is.

2022-09-12 09:51 UTC, ESapenaVentura commented on json_schema/core/file/file_core.json
> +                "HCA Ingest"
That sounds good to me, I will commit the change!

2022-09-12 12:45 UTC, ncalvanese1 commented on json_schema/core/file/file_core.json
>              "guidelines": "Should be one of: DCP/2 Analysis, Contributor, ArrayExpress, HCA Release, GEO, SCEA, SCP, DCP/1 Matrix Service, LungMAP, Zenodo, Publication",
Should the guidelines be updated to reflect the updated enum?

2022-09-12 13:41 UTC, ESapenaVentura commented on json_schema/core/file/file_core.json
>              "guidelines": "Should be one of: DCP/2 Analysis, Contributor, ArrayExpress, HCA Release, GEO, SCEA, SCP, DCP/1 Matrix Service, LungMAP, Zenodo, Publication",
You mean https://github.com/HumanCellAtlas/dcp2/pull/66?

2022-09-12 14:15 UTC, ncalvanese1 commented on json_schema/core/file/file_core.json
>              "guidelines": "Should be one of: DCP/2 Analysis, Contributor, ArrayExpress, HCA Release, GEO, SCEA, SCP, DCP/1 Matrix Service, LungMAP, Zenodo, Publication",
I actually meant the "guidelines" property in the json here. It seems like it lists the enums (which in itself may be a bit redundant), but it wasn't updated the include the additional enum value.

2022-09-12 16:38 UTC, hannes-ucsc commented on json_schema/core/file/file_core.json
>              "guidelines": "Should be one of: DCP/2 Analysis, Contributor, ArrayExpress, HCA Release, GEO, SCEA, SCP, DCP/1 Matrix Service, LungMAP, Zenodo, Publication",
I'll update the spec PR.

2022-09-12 16:39 UTC, hannes-ucsc requested changes

2022-09-12 16:39 UTC, hannes-ucsc commented on docs/jsonBrowser/core.md
> +file_source | The source of the file. This is typically an organisation, repository, person or dedicated process. | string | no |  | File source | DCP/2 Analysis, Contributor, ArrayExpress, HCA Relea
```suggestion
file_source | The source of the file. This is typically an organisation, repository, person or dedicated process. | string | no |  | File source | DCP/2 Analysis, Contributor, ArrayExpress, HCA Release, GEO, SCEA, SCP, DCP/1 Matrix Service, LungMAP, Zenodo, Publication, DCP/2 Ingest | GEO; Contributor
```

2022-09-13 08:31 UTC, amnonkhen approved these changes

2022-09-13 12:05 UTC, ESapenaVentura commented on json_schema/core/file/file_core.json
>              "guidelines": "Should be one of: DCP/2 Analysis, Contributor, ArrayExpress, HCA Release, GEO, SCEA, SCP, DCP/1 Matrix Service, LungMAP, Zenodo, Publication",
Oh, apologies @ncalvanese1 I read this as a standalone comment and did not realise you were referring to the "guidelines" field. 

I will address this comment and Hannes' suggestion on the markdown file

2022-09-13 12:36 UTC, ncalvanese1 approved these changes
Looks good to me, thanks!

2022-09-14 01:08 UTC, hannes-ucsc approved these changes

2022-09-15 18:34 UTC, NoopDog approved these changes

2022-09-16 10:42 UTC, amnonkhen commented on json_schema/update_log.csv
> +core/file/file_core,minor,"Added value to enum for file source. Fixes #1487.",,
Do we need a value in the date column?

2022-09-16 10:43 UTC, amnonkhen approved these changes

2022-09-16 10:55 UTC, ESapenaVentura commented on json_schema/update_log.csv
> +core/file/file_core,minor,"Added value to enum for file source. Fixes #1487.",,
No, we don't! it gets filled automatically by the `src/release_prepare.py` script. We just need an empty value

2022-09-16 11:04 UTC, merged