Added timecourse to remaining biomatierals. Fixes #1511
HumanCellAtlas/metadata-schema pull request #1513
Opened 2023-02-22 23:07 UTC by rachadele

### Release notes

For `type/biomaterial/specimen_from_organism.json` schema:
-Added timecourse module

For `type/biomaterial/imaged_specimen.json` schema:
-Added timecourse module

For `type/biomaterial/organoid.json` schema:
-Added timecourse module

### Reviews requested

-Minor change, adding timecourse to specimen, organoid and imaged specimen biomaterials

2023-02-24 21:09 UTC, NoopDog commented
Hi @willrockout If we are adding this to all biomaterials, why not add to [biomaterial core](https://data.humancellatlas.org/metadata/dictionary/biomaterial/biomaterial_core) instead?
Cheers,
D

2023-02-24 21:17 UTC, willrockout commented
@NoopDog I was a bit torn on that too. I think because it's a module I was thinking of separating them. @ESapenaVentura thoughts? Not sure if changing the biomaterial core would have any other effects.

2023-03-02 22:46 UTC, willrockout commented
@NoopDog My reasoning was that the core entities were designed to be fields that are always filled out such as id, name, and taxon id. In the case of timecourse, the reason it's a module is that not every experimental design will have that component. @tburdett correct me if I'm wrong about the original intent of core, type, and module.

2023-03-06 19:57 UTC, ncalvanese1 approved these changes
Looks good to me!

2023-03-06 22:55 UTC, hannes-ucsc reviewed
The core schema already has several optional properties so optionality shouldn't stop us from putting timecourse into biomaterial core. Also, it can remain a module and still be referenced in the core schema. There's no contradiction there either. 

Think what would happen if we added a new, concrete biomaterial type. Is it more likely that we'd want to support timecourse in that new type or not? If so, timecourse should go into the core schema. The counter argument to putting everything in the core schema (and making it optional there) is that it makes the core schema larger and harder to understand. If you already know there will be biomaterial types for which timecourse categorically makes no sense, then I wouldn't put it in the core schema, but instead in each concrete schema where I know timecourse makes sense. I don't know enough about the biology to decide that. Last thought: Another argument for not putting a property into the core schema is if doing so allows you to make it required in some of them (thereby adding specificity).

2023-03-07 18:15 UTC, willrockout commented
I think what @hannes-ucsc says makes sense. I can't think of any examples where you'd have a biomaterial that couldn't possibly have a timecourse component. The last thing I want to check before fixing this PR is backward compatibility and the new spreadsheet creation. @amnonkhen @ESapenaVentura Would this cause any issues with projects that have timecourse filled out since this would change programmatic names?

2023-03-15 17:08 UTC, willrockout commented
Alright, I have changed the timecourse module to be in the biomaterial core and removed it from the individual biomaterial types. @ncalvanese1 @hannes-ucsc @NoopDog @ESapenaVentura @amnonkhen Can you please review again?

2023-03-15 17:22 UTC, hannes-ucsc approved these changes

2023-03-17 05:26 UTC, NoopDog approved these changes

2023-03-21 09:16 UTC, ESapenaVentura requested changes
The changes to the schemas LGTM, just 2 comments:

- Missing lines in update_log.csv (See comment)
- property_migrations.json needs to be updated with the "moved" property (Happy to help with that if you're unsure how to update it)

2023-03-21 09:16 UTC, ESapenaVentura commented on json_schema/update_log.csv
> +core/biomaterial/biomaterial_core,minor,Added timecourse module. Fixes #1511,,
We also need the lines for the biomaterials that lost the "timecourse" property (Major change, since a property was deleted)

2023-03-29 16:18 UTC, willrockout commented
@NoopDog @ESapenaVentura @hannes-ucsc @ncalvanese1 @amnonkhen Final updates have happened if you can review them one more time?

2023-03-29 18:07 UTC, ncalvanese1 approved these changes

2023-03-31 10:40 UTC, ESapenaVentura approved these changes
LGTM, just a note on internal processes, the script that updates the log/the versions should be run right before merging.

This is to allow for multiple PRs to be operating at the same time, as if another PR closes earlier and bumps the versions of the same entities, you can bump over them right before merging!

I think in this case it should be ok because we don't have anything going on for biomaterials at the moment, but just so you know!

2023-04-03 16:44 UTC, hannes-ucsc approved these changes

2023-04-03 19:23 UTC, NoopDog approved these changes

2023-07-12 11:54 UTC, amnonkhen approved these changes

2023-07-20 16:44 UTC, rachadele commented on json_schema/update_log.csv
why was this deleted?

2023-07-25 22:11 UTC, willrockout commented
Fixed schema versions issues so no need for re-review.

2023-07-26 16:47 UTC, hannes-ucsc requested changes
> Update fixed schema versions issues so no need for re-review.

The SOP requires re-review after every change. Not every small change is trivial. If the changes are trivial, then reviewing them can be done in a minute.

2023-07-26 16:47 UTC, hannes-ucsc commented on changelog.md
> +<<<<<<< HEAD
These conflict markers should not be here.

2023-07-26 18:25 UTC, willrockout commented
This has been moved to PR #1529.

2023-07-26 18:25 UTC, closed without merging