Added HCA Tissue Atlas, HCA Tissue Atlas Version, Project Integrated Status, and HCA Project uuid field. Fixes #1517
HumanCellAtlas/metadata-schema pull request #1518
Opened 2023-03-16 15:58 UTC by Wkt8

### Release notes

For module/project/publication.json schema:
- Added `hca_tissue_atlas` field
- Added `integrated_status` field
- Added `hca_tissue_atlas_version` field
- Added `hca_project_uuid` field
 
### Why are these changes needed?

This change is needed for data contributors and consumers, to identify projects part of an official HCA Tissue Atlas, to identify the Atlas Project which integrates other analysis files, denote the version of the HCA Tissue Atlas, and describe the uuid of the associated HCA Project 

### Reviews requested

- Need Reviewers to approve because this is a minor update

We have planned the four metadata schema fields to explicitly describe the metadata of the project. [Wrangler meeting notes](https://docs.google.com/document/d/1N3dJA5dQuJcY5pxhT2pNgwZptKfdH3BSsqZSnWD0nUo/edit#)
[Example spreadsheet](https://docs.google.com/spreadsheets/d/1CiyCJZ96lu3PBLr7RAgbz08h1qA66n0Z/edit?usp=sharing&ouid=114069941208994528669&rtpof=true&sd=true)

2023-03-16 17:53 UTC, idazucchi reviewed
Hi! 
The PR looks good but I have a question about the versioning. Does it have to be in the format vX.X? Wouldn't a single number be enough?

If we want to keep the dot notation I would suggest adding a reular expression to avoid spelling variants (spaces, capitalisation and other mistakes)

2023-03-16 17:53 UTC, idazucchi commented on json_schema/module/project/publication.json
> +            "description": "A field describing if the project is part of an HCA Tissue Atlas (e.g. Kidney). Enter ‘No’ if the project is not part of an HCA Tissue Atlas.",
```suggestion
            "description": "A field describing if the project is part of an official HCA Tissue Atlas (e.g. Kidney). Enter ‘No’ if the project is not part of an official HCA Tissue Atlas.",
```

2023-03-16 17:53 UTC, idazucchi commented on json_schema/module/project/publication.json
> +                "Pancrease",
```suggestion
                "Pancreas",
```

2023-03-16 17:53 UTC, idazucchi commented on json_schema/module/project/publication.json
> +            "description": "A field describing if the HCA Tissue Atlas project integrates data from other projects. ",
```suggestion
            "description": "A field describing if the HCA Tissue Atlas project is the result of dataset integration. ",
```

2023-03-20 10:22 UTC, anu-shiva reviewed
Do we also want to add the year-month of the release (as it makes it a bit simpler  for the contributors to understand the  releases in addition to the atlas version )

2023-03-28 14:09 UTC, ESapenaVentura requested changes

2023-03-28 14:09 UTC, ESapenaVentura commented on json_schema/module/project/publication.json
> +            "pattern": "v[0-9].[0-9]",
```suggestion
            "pattern": "^v[0-9]+\\.[0-9]+$",
```

2023-04-04 10:39 UTC, Wkt8 commented
Closing PR without merging and creating a new one due to conversations between EBI wranglers, UCSC wranglers, and Dave.

2023-04-04 10:39 UTC, closed without merging