Added hca_bionetwork module to Project. Fixes #1517
HumanCellAtlas/metadata-schema pull request #1520
Opened 2023-04-05 10:20 UTC by Wkt8

### Release notes
Added module/project/hca_bionetwork.json schema:
- Added `names` field
- Added `hca_tissue_atlas` field
- Added `hca_tissue_atlas_version` field
- added `atlas_project` field

### Why are these changes needed?

This change is needed for data contributors and consumers, to describe if this project is part of a HCA bionetwork, is part of a HCA Atlas, what version of the atlas, and whether it is the 'Atlas Project' containing a h5ad file that draws from other projects or not. 

### Reviews requested

- Need Reviewers to approve because this is a minor update

Discussion here: https://miro.com/app/board/uXjVMfMlgLc=/
We have planned the four metadata schema fields to explicitly describe the metadata of the project. [Wrangler meeting notes](https://docs.google.com/document/d/1N3dJA5dQuJcY5pxhT2pNgwZptKfdH3BSsqZSnWD0nUo/edit#)
[Example spreadsheet](https://docs.google.com/spreadsheets/d/1CiyCJZ96lu3PBLr7RAgbz08h1qA66n0Z/edit?usp=sharing&ouid=114069941208994528669&rtpof=true&sd=true)

2023-04-05 20:27 UTC, hannes-ucsc requested changes

2023-04-05 20:27 UTC, hannes-ucsc commented on json_schema/module/project/hca_bionetwork.json
> +            "enum": ["Yes","No"],
```suggestion
            "type": "boolean",
```

right?

2023-04-05 20:27 UTC, hannes-ucsc commented on json_schema/module/project/hca_bionetwork.json
> +            "pattern": "^[0-9]{1,}.[0-9]{1,}.[0-9]{1,}$",
```suggestion
            "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$",
```

2023-04-05 20:27 UTC, hannes-ucsc commented on json_schema/module/project/hca_bionetwork.json
> +            "pattern": "v[0-9].[0-9]",
```suggestion
            "pattern": "^v[0-9]+\\.[0-9]+$",
```

But even with these corrections, the pattern would allow non-sensical strings like v0000.09

I recommend breaking this up into two separate integer properties, one for the major version and one for the minor version.

2023-04-05 20:27 UTC, hannes-ucsc commented on json_schema/module/project/hca_bionetwork.json
> +                "No"
```suggestion
                "None"
```

 or 
 
 ```suggestion
                "N/A"
```

2023-04-05 20:27 UTC, hannes-ucsc commented on json_schema/module/project/hca_bionetwork.json
> +            "type": "string",
Fields like this are bound to end up with misspelled, inconsistently spelled values. Can you make this an enum or do you have something else planned to quality-control this field?

2023-04-06 13:58 UTC, ESapenaVentura requested changes
Left some comments!

2023-04-06 13:58 UTC, ESapenaVentura commented on json_schema/module/project/hca_bionetwork.json
> +        "Names": {
```suggestion
        "name": {
```

2023-04-06 13:58 UTC, ESapenaVentura commented on json_schema/module/project/hca_bionetwork.json
> +            "user_friendly": "Official HCA Bionetwork(s)",
```suggestion
            "user_friendly": "Official HCA Bionetwork",
```

2023-04-06 13:58 UTC, ESapenaVentura commented on json_schema/module/project/hca_bionetwork.json
> +            "type": "string",
@hannes-ucsc I think we are currently discussing about this. So far (Please @Wkt8 and @idazucchi correct me if I'm wrong) we have no official listing.

2023-04-06 13:58 UTC, ESapenaVentura commented on json_schema/module/project/hca_bionetwork.json
> +            "pattern": "v[0-9].[0-9]",
would 
```suggestion
            "pattern": "^v(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$",
```

work better? Although I am not opposed against creating a "major" and "minor" version, we should probably discuss about this @Wkt8

2023-04-06 13:58 UTC, ESapenaVentura commented on json_schema/update_log.csv
> +module/project/hca_bionetwork,minor,"Added the hca_bionetwork module with four fields for recording bionetwork and atlas information",,
https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/committers.md#specific-how-to-for-making-changes , point 5, new schemas only

tl;dr, this should be marked as a major change because we're adding a module. For the project entity this is minor, but the module should start in version 1.0.0 :)

2023-04-06 14:00 UTC, ESapenaVentura commented on json_schema/type/project/project.json
> +        },
```suggestion
        "hca_bionetworks": {
            "description": "HCA Bionetworks and Atlases the project is associated with",
            "type": "array",
            "items": {
                "$ref": "module/project/hca_bionetwork.json"
            },
            "user_friendly": "HCA Bionetwork(s)"
        },
```

2023-04-06 14:26 UTC, Wkt8 commented on json_schema/module/project/hca_bionetwork.json
> +            "description": "A field describing which HCA Bionetwork the project is a part of (e.g. Kidney). Enter ‘No’ if the project is not part of an official HCA Bionetwork.",
```suggestion
            "description": "A field describing which HCA Bionetwork the project is a part of (e.g. Kidney). Enter ‘None’ if the project is not part of an official HCA Bionetwork.",
```

2023-04-06 14:32 UTC, idazucchi commented on json_schema/module/project/hca_bionetwork.json
> +            "type": "string",
We are hoping to get a list of the first few tissue atlases after the meeting on Friday with the advisory board, but this enum field will have to be updated in the future as the atlases are assembled.

2023-04-06 14:32 UTC, Wkt8 commented on json_schema/module/project/hca_bionetwork.json
> +            "pattern": "v[0-9].[0-9]",
I think also because the bionetworks haven't given us any guidelines on 'what a major or minor version looks like' we're trying to future-proof by adding in major and minor version storage in our metadata schema, but we don't even know if they'll have major and minor versions.

2023-04-06 14:33 UTC, Wkt8 commented on json_schema/update_log.csv
> +module/project/hca_bionetwork,minor,"Added the hca_bionetwork module with four fields for recording bionetwork and atlas information",,
```suggestion
module/project/hca_bionetwork,major,"Added the hca_bionetwork module with four fields for recording bionetwork and atlas information",,

```

2023-04-07 22:25 UTC, hannes-ucsc commented on json_schema/module/project/hca_bionetwork.json
> +            "type": "string",
If we could settle on an initial list of possible values, I'd obviously prefer an enum field. PRs that add entries to enums will be easy to review and merge.

2023-04-11 15:37 UTC, ncalvanese1 approved these changes

2023-04-12 14:07 UTC, Wkt8 commented on json_schema/module/project/hca_bionetwork.json
> +            "description": "A field describing which version of the HCA Tissue Atlas is associated with the projet (e.g. v1.0; v2.0)",
```suggestion
            "description": "A field describing which version of the HCA Tissue Atlas is associated with the project (e.g. v1.0; v2.0)",
```

2023-04-12 14:15 UTC, Wkt8 commented on json_schema/module/project/hca_bionetwork.json
> +            "type": "string",
This field has been changed to an enum with three initial values - Blood, Retina, and None. More to come as we learn more from the Bionetworks!

2023-04-14 12:36 UTC, ESapenaVentura requested changes
Added some comments!

Please take special attention to the field description comment, it applies to all of the descriptions for the newly created fields

2023-04-14 12:36 UTC, ESapenaVentura commented on json_schema/module/project/hca_bionetwork.json
> +            "description": "A field describing which HCA Bionetwork the project is a part of (e.g. Kidney). Enter ‘None’ if the project is not part of an official HCA Bionetwork.",
```suggestion
            "description": "Name of the HCA Bionetwork the associated project is a part of (e.g. Kidney).",
```

I wouldn't use "A field ..." for the description, there's nothing in the guidelines but it sounds a little weird to me! Also the `Enter ‘None’ if the project is not part of an official HCA Bionetwork.` seems more fit in the guidelines :)

2023-04-14 12:36 UTC, ESapenaVentura commented on json_schema/module/project/hca_bionetwork.json
> +    ],
Won't there be any required property? If so, we can just delete this field

2023-04-14 12:36 UTC, ESapenaVentura commented on json_schema/module/project/hca_bionetwork.json
> +                "None"
```suggestion
                "Skin"
```
If this field is not required, I would delete "None" from the list!

2023-04-14 12:36 UTC, ESapenaVentura commented on json_schema/module/project/hca_bionetwork.json
> +            "guidelines": "Should be one of the networks from https://www.humancellatlas.org/biological-networks/ or 'No' if not a network",
```suggestion
            "guidelines": "Should be one of the networks from https://www.humancellatlas.org/biological-networks/ or 'None' if not a network",
```

Also we can delete this depending on the comment above

2023-04-14 12:36 UTC, ESapenaVentura commented on json_schema/module/project/hca_bionetwork.json
> +                "None"
If this field is not required, I would not add the "None" option

2023-04-14 12:36 UTC, ESapenaVentura commented on json_schema/module/project/hca_bionetwork.json
> +            "example": "Atlas Project; No"
```suggestion
            "example": "Yes; No"
```

2023-04-17 17:38 UTC, hannes-ucsc commented on json_schema/module/project/hca_bionetwork.json
> +                "None"
> If this field is not required, I would delete "None" from the list!

(from https://github.com/HumanCellAtlas/metadata-schema/pull/1520/files#r1166781046)

What would be the difference, semantically speaking, between `"name": "None"` and the `name` property being absent? Downstream in the Data Browser this would render as `Unspecified` vs `None`. If this distinction isn't meaningful, then I'd have to agree with @ESapenaVentura.

2023-04-18 03:16 UTC, NoopDog approved these changes

2023-04-19 10:53 UTC, ESapenaVentura approved these changes
LGTM

2023-04-19 15:52 UTC, hannes-ucsc approved these changes

2023-04-20 11:55 UTC, merged