dcp-954 fix hca_bionetwork schema url
HumanCellAtlas/metadata-schema pull request #1526
Opened 2023-06-29 21:43 UTC by amnonkhen

schema url (`describedBy`) pattern was incorrect

dcp-954
ebi-ait/dcp-ingest-central#954

2023-06-30 13:47 UTC, ncalvanese1 approved these changes
LGTM!

2023-06-30 15:29 UTC, ESapenaVentura requested changes
It's missing writing the changes in the update_log.csv - Also not sure if the human-readable markdowns have been generated 

Here is a document with the specifics on what is expected that is done during an update https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/committers.md#specific-how-to-for-making-changes, but we can discuss on monday if it's unclear!

2023-06-30 18:25 UTC, hannes-ucsc requested changes
Title is misleading. This cannot be an expedited review. See section 1.6.1 of the SOP.

2023-07-05 22:10 UTC, NoopDog approved these changes
Nice ! ⭐

2023-07-20 17:25 UTC, hannes-ucsc approved these changes

2026-02-27 15:53 UTC, closed without merging