Removed timecourse from types and added to biomaterial core. Fixes #1511
HumanCellAtlas/metadata-schema pull request #1529
Opened 2023-07-26 17:36 UTC by willrockout

### Release notes

This is a remake of PR #1513 to clean up the commit tree.

For core/biomaterial/biomaterial_core.json schema:
-Added timecourse module

For type/biomaterial/donor_organism.json schema:
-Removed timecourse module

For type/biomaterial/cell_suspension.json schema:
-Removed timecourse module

For type/biomaterial/cell_line.json schema:
-Removed timecourse module

Reviews requested
-Major change, removing timecourse module from donor_organism, cell_line, and cell_suspension.
-Minor change, adding timecourse module to biomaterial core.

2023-07-27 23:32 UTC, hannes-ucsc requested changes

2023-07-27 23:32 UTC, hannes-ucsc commented on json_schema/core/biomaterial/biomaterial_core.json
> +            "description": "Information relating to a timecourse associated with this cell line.",
```suggestion
            "description": "Information relating to a timecourse associated with this biomaterial.",
```

2023-07-28 06:46 UTC, amnonkhen approved these changes

2023-07-28 17:33 UTC, hannes-ucsc requested changes
~Shouldn't this have been~

2023-07-28 17:33 UTC, hannes-ucsc commented on docs/jsonBrowser/core.md
> +timecourse | Information relating to a timecourse associated with this cell line. | object | no | [See module  timecourse](module.md#timecourse) | Timecourse |  |
```suggestion
timecourse | Information relating to a timecourse associated with this biomaterial. | object | no | [See module  timecourse](module.md#timecourse) | Timecourse |  | 
```

I thought the documentation was automatically generated from the schema, so making the schema change I proposed in my previous review should have automatically caused this line to be updated, too.

2023-07-28 17:45 UTC, willrockout commented on docs/jsonBrowser/core.md
> +timecourse | Information relating to a timecourse associated with this cell line. | object | no | [See module  timecourse](module.md#timecourse) | Timecourse |  |
I believe it is automatically created with Git hooks upon a push but I'm not 100%. It seems to not work from a GitHub commit.

2023-07-28 18:11 UTC, willrockout commented on docs/jsonBrowser/core.md
> +timecourse | Information relating to a timecourse associated with this cell line. | object | no | [See module  timecourse](module.md#timecourse) | Timecourse |  |
Fixed

2023-07-28 18:13 UTC, hannes-ucsc commented on docs/jsonBrowser/core.md
> +timecourse | Information relating to a timecourse associated with this cell line. | object | no | [See module  timecourse](module.md#timecourse) | Timecourse |  |
> It seems to not work from a GitHub commit.

Well, that's a problem.

2023-07-28 18:16 UTC, hannes-ucsc commented on docs/jsonBrowser/core.md
> +timecourse | Information relating to a timecourse associated with this cell line. | object | no | [See module  timecourse](module.md#timecourse) | Timecourse |  |
Procedural comment: The author shouldn't resolve reviewer comments. Reviewers resolve their own comments when they feel they have been addressed.

From the [SOP](https://github.com/HumanCellAtlas/dcp2/blob/main/docs/dcp2_operating_procedures.rst#id8):

> If you accept the PR author's response to a comment made by the reviewer, mark the comment thread as resolved on Github.

2023-07-28 18:17 UTC, hannes-ucsc approved these changes

2023-08-01 12:10 UTC, ncalvanese1 approved these changes

2023-08-01 13:40 UTC, ESapenaVentura approved these changes
LGTM!! Just a question - Based on the comments above, do I take that you manually corrected the `docs/jsonBrowser/core.md` doc?

2023-08-01 17:09 UTC, hannes-ucsc commented
@ESapenaVentura, in my experience, commit hooks aren't a good enforcement mechanism, simply because they can easily be bypassed. What we do in my projects is make the code/doc generation part of our build process and then have a validation step in our GitHub Actions workflow that tests for a dirty working copy. If the author of a change forgets to run the code/doc generation and commit the result, the code generation will dirty the working copy on CI/CD and fail the GitHub Actions workflow. This has worked very well for us in a number of different scenarios. For example,  we also detect stale transitive Python dependencies that way.

2023-08-01 18:42 UTC, willrockout commented
@ESapenaVentura Yes I changed it from the command line on my local copy then committed and pushed the change but for the change to the biomaterial_core.json I made the change on Git Hub.

2023-08-22 18:38 UTC, merged