Added transplant field to specimen_from_organism. Fixes #1531
HumanCellAtlas/metadata-schema pull request #1532
Opened 2023-09-04 17:04 UTC by idazucchi

### Release notes

For `specimen_from_organism.json` schema:
- added `transplant` field

### Why are these changes needed?
 The new field is needed to clearly indicate whether the sampled tissue comes from a transplanted organ. This field was requested by the kidney Bionetwork.

### Reviews requested
This is a minor schema changes, all DCP2 reviewers need to review

2023-09-05 11:27 UTC, amnonkhen commented
Should `versions.json` be modified as well?

2023-09-05 11:33 UTC, amnonkhen requested changes

2023-09-05 11:33 UTC, amnonkhen commented on json_schema/type/biomaterial/specimen_from_organism.json
> +            ],
Have you considered using an ontology term? sych as http://purl.obolibrary.org/obo/NCIT_C12981

2023-09-05 12:59 UTC, ESapenaVentura commented on json_schema/type/biomaterial/specimen_from_organism.json
> +            ],
not a bad idea - Could live under the class that amnon mentions, although that means we may accept terms we don't expect there

2023-09-08 09:48 UTC, idazucchi commented on json_schema/type/biomaterial/specimen_from_organism.json
> +            ],
the aim of the transplant field is to highlight if a tissue was sampled from a different donor. This has two implications:
1. the tissue has a different genetic background from other specimens from the same donor
2. the tissue can contain cell from both the transplant donor and the recipient. This is particularly important for a xenografts because some reads will need to be mapped to a different reference genome

The two terms Allograft and Xenograft convey enough information on the two points above. 
The other terms in the ontology branch are subtypes of either, or possibly both since the description doesn't clearly state if the graft is done within the same species (Cadaveric Venous Graft, Organ Graft, Free Arterial Graft). They add context on the medical/surgical procedure but don't add information that's relevant for the two points above and in most cases lack information on whether the tranplant is an allograft or xenograft.

For these reasons I'm against ontologising the field

2023-09-08 15:43 UTC, hannes-ucsc commented on json_schema/type/biomaterial/specimen_from_organism.json
> +            ],
> I'm against ontologising the field because I don't think that it would add a lot of useful information

As far as I understand it, the motivation behind ontologising a field is to eliminate the need for schema (and metadata) updates when terms are added or updated, and to avoid inconsistencies between the schema enum and any ontologies that might already exist now, or that might be added in the future.

> but rather it would make distinguishing between allograft and xenograft less easy

We will ultimately solve this in Azul/Data Browser. Users will be able to search by an ancestor term and that search will return references to any descendant term. It might be a while until this is implemented but we should take the long-term view here unless there is a good reason not to.

2023-09-11 17:32 UTC, idazucchi commented on json_schema/type/biomaterial/specimen_from_organism.json
> +            ],
It's true that ontologizing a field can help avoid future updates, but in this case I can't imagine what other field we might want to add. Either the transplanted tissue comes from the same species or it comes from a different one. There might be artificial prothesis but those don't have cells that can be sequenced.

>but rather it would make distinguishing between allograft and xenograft less easy

search by an ancestor term won't enable users to distinguish xenograft from allograft because of the ontology's structure: all terms under [graft](https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C12981?lang=en) are siblings and are not under either xenograft or allograft. It is necessary to use xenograft or allograft to specify explicitly if the donor and transplant recipient are from the same species

<img width="592" alt="Screenshot 2023-09-11 at 18 21 13" src="https://github.com/HumanCellAtlas/metadata-schema/assets/45209056/a4fd9436-d5f8-42b1-ac56-19a73b3fff69">

2023-09-12 19:36 UTC, NoopDog commented on json_schema/type/biomaterial/specimen_from_organism.json
> +            ],
Hi @idazucchi, I feel this and all other fields should be ontologized if possible. We don't need to allow all values from the ontology.  The graph restriction section should let us specify that we only accept Allograft and Xenograft and their children.

2023-09-20 05:34 UTC, NoopDog commented on json_schema/type/biomaterial/specimen_from_organism.json
> +            ],
Hi @Wkt8 is there extra effort to ontologize the field? Also, for my knowledge, why do you feel we will not have the benefit of interoperability in this case? Thanks! D

2024-03-18 17:10 UTC, hannes-ucsc commented
I assume this is superseded by https://github.com/HumanCellAtlas/metadata-schema/pull/1548 so I am closing it. If I'm wrong, please just reopen.

2024-03-18 17:10 UTC, closed without merging