Added alignment_software & alignment_software_version field in analysis_file Fixes #1533
HumanCellAtlas/metadata-schema pull request #1534
Opened 2023-10-13 10:04 UTC by arschat

### Release notes

For `analysis_file.json` schema:
- Added `alignment_software` required field
- Added `alignment_software_version` field

### Why are these changes needed?

This field is needed to record the specific software used in order to align fastq files to a reference genome.
Is one of the upcoming Tier 1 metadata proposed from HCA Integration Teams & HCA Bionetworks.

2023-10-17 11:31 UTC, idazucchi approved these changes
Looks good!
for `alignment_software` : unfortunately there is no ontology that covers alignment software, and and enum would probably require a lot of updates. I think free text in this case is a good choice

2023-10-18 09:48 UTC, ESapenaVentura requested changes
Added some comments :)

2023-10-18 09:48 UTC, ESapenaVentura commented on changelog.md
> +
this is filled by the release_prepare.py script

2023-10-18 09:48 UTC, ESapenaVentura commented on json_schema/versions.json
> +                "analysis_file": "8.0.0",
This is filled by the release_prepare.py script

2023-10-18 09:48 UTC, ESapenaVentura commented on json_schema/type/file/analysis_file.json
> +            "guidelines": "Please use name of alignment software or \\'Not Applicable\\' if no alignment software was used for this file",
escaping not needed

2023-10-18 09:48 UTC, ESapenaVentura commented on json_schema/type/file/analysis_file.json
> +            "guidelines": "Please use version of alignment software or \\'Not Applicable\\' if no alignment software was used or version was not provided for this file",
escaping not needed

2023-10-18 09:48 UTC, ESapenaVentura commented on json_schema/type/file/analysis_file.json
> +        "alignment_software"
is the version not required?

2023-10-18 09:48 UTC, ESapenaVentura commented on json_schema/type/file/analysis_file.json
> +            "description": "Name of alignment software used to map FASTQ files to reference genome",
Missing dot at the end

2023-10-18 09:48 UTC, ESapenaVentura commented on json_schema/type/file/analysis_file.json
> +            "description": "Version of alignment software used to map FASTQ files to reference genome",
Missing dot at the end

2023-10-18 15:17 UTC, arschat commented on json_schema/type/file/analysis_file.json
> +        "alignment_software"
Initially though about making it optional like the genome_version_patch but since version is required in Tier 1 metadata too, its better to have it required too (for cases like Cell Ranger 7.0 introducing intron counting by default).

2023-10-23 17:11 UTC, hannes-ucsc reviewed
Shouldn't this be modeled as a property of the analysis protocol type? Imagine you have hundreds of BAMs in a project that were all aligned by the same software and version, do you really want to specify the aligner for every file?

2023-10-24 09:12 UTC, arschat commented
@hannes-ucsc Hello Hannes! My initial thought was to accompany the aligner with the genome assembly version, and since genome assembly version field is recorded in the analysis file, I modeled it that way. I can see the pros of modeling it in the analysis protocol, and if you agree on separating `alignment_software` and `genome_assembly_version` I will proceed with the proposed change.

2023-10-24 17:57 UTC, hannes-ucsc commented
> and if you agree on separating `alignment_software` and `genome_assembly_version` I will proceed with the proposed change

Did you mean "`alignment_software` and `alignment_software_version`"?

And with "proposed change" you mean moving `alignment_software` and `alignment_software_version` to `analysis_protocol`?

2023-10-25 08:57 UTC, arschat commented
Exactly. If you agree on separating `alignment_software` and `alignment_software_version` from `genome_assembly_version` I will proceed with moving the two new fields in the `analysis_protocol` type. Sorry for not being clear before.

2023-10-25 09:22 UTC, amnonkhen approved these changes

2023-10-25 17:12 UTC, hannes-ucsc commented
Great, that's the approach I find most reasonable.

2023-10-26 18:08 UTC, hannes-ucsc requested changes

2023-10-26 18:08 UTC, hannes-ucsc commented on json_schema/type/protocol/analysis/analysis_protocol.json
> +        "alignment_software_version"
Since `analysis_protocol` is so general, any properties that don't apply to *every* type of analysis protocol should be left optional. That's already the precedent so far in this schema. That will also eliminate the need to invent special (and unconstrained) escape hatches such as `Non applicable` below. This wouldn't be the first time that a wrangler mistypes "Non Applicable", leading to very obviously visible garbage in the Data Browser, if it were to display all existing values for this property.   

In an ideal world, there would be a subtype schema called `alignment_protocol` and potentially even an `aligned_sequence_file` subtype of `analysis_file` but that would be much more work.

2023-10-27 16:41 UTC, hannes-ucsc commented
[Note https://github.com/HumanCellAtlas/dcp2/blob/main/docs/dcp2_operating_procedures.rst](https://github.com/HumanCellAtlas/dcp2/blob/main/docs/dcp2_operating_procedures.rst#pull-request-reviews) step 9

> 9. Start another cycle by requesting a review from the reviewers currently on the PR, *even those that already approved the PR* or just commented on it. Proceed to step 3.

2023-10-27 16:45 UTC, NoopDog approved these changes

2023-10-31 09:46 UTC, amnonkhen approved these changes
LGTM

2023-10-31 13:52 UTC, ESapenaVentura requested changes
Added a couple comments, overall LGTM but need to change `dependentRequired` for `dependencies` and add some minor corrections to the update_log!

2023-10-31 13:55 UTC, ESapenaVentura commented on json_schema/type/protocol/analysis/analysis_protocol.json
> +    "dependentRequired": {
(More info about the `dependencies` split: https://json-schema.org/draft/2019-09/release-notes#semi-incompatible-changes)

2023-10-31 14:20 UTC, arschat commented on json_schema/type/protocol/analysis/analysis_protocol.json
> +    "dependentRequired": {
Thanks for that comment.
The dependency was there to prevent having only `alignment_software_version` without `alignment_software`. There are cases where only the software name is provided in the publication and I believe we should have this option.

2023-10-31 15:48 UTC, ESapenaVentura approved these changes
LGTM

2023-10-31 17:55 UTC, hannes-ucsc approved these changes

2023-10-31 18:36 UTC, NoopDog approved these changes

2023-11-01 11:05 UTC, amnonkhen approved these changes

2023-11-07 13:44 UTC, ncalvanese1 approved these changes

2023-11-07 15:26 UTC, merged