Added organ_donor field in donor_organism. Fixes#1547
HumanCellAtlas/metadata-schema pull request #1548
Opened 2024-02-16 12:01 UTC by arschat

### Release notes

For `type/biomaterial/donor_organism` schema:
- added `organ_donor` field
 

### Reviews requested

- This is a minor schema change, all DCP2 [designated reviewers](https://github.com/HumanCellAtlas/dcp2/blob/main/docs/dcp2_operating_procedures.rst#163designated-reviewers) need to review.

2024-03-08 05:08 UTC, hannes-ucsc approved these changes

2024-03-08 07:54 UTC, NoopDog approved these changes

2024-03-08 11:24 UTC, ESapenaVentura requested changes
I think this field would be better suited in the Specimen, given multiple specimens can be taken from a donor and not all of them may come from a transplanted organ

2024-03-08 17:54 UTC, hannes-ucsc commented on json_schema/type/biomaterial/specimen_from_organism.json
> +        "organ_donor": {
```suggestion
        "transplanted_organ": {
```

And unless you have a policy of always appending fields to the schema, should this be inserted after organ_parts?

2024-03-08 17:54 UTC, hannes-ucsc commented on json_schema/type/biomaterial/specimen_from_organism.json
> +            "description": "Was the specimen collected after extraction for organ transplantation?",
```suggestion
            "description": "Was the specimen collected after extraction for organ transplantation?",
```

Does it matter if collection happened before or after extraction?

```suggestion
            "description": "Was the specimen collected from an organ about to be transplanted to another organism?",
```

2024-03-08 18:04 UTC, hannes-ucsc commented
Note that these are questions/suggestions, not requested changes.

2024-03-11 13:53 UTC, arschat commented on json_schema/type/biomaterial/specimen_from_organism.json
> +            "description": "Was the specimen collected after extraction for organ transplantation?",
Hi Hannes, bionetworks are interested in recording this since despite that this is not specimen from a living organism (in most transplant cases) the tissue is kept alive and therefore the transcriptome quality of the sample is in much better condition that to a post-mortem sample.

Therefore, yes, it is important to record that when collection happened after extraction.

2024-03-11 14:00 UTC, arschat commented on json_schema/type/biomaterial/specimen_from_organism.json
> +        "organ_donor": {
`transplanted_organ` might be interpreted as the specimen was collected from a transplanted organ (after successful transplantation) rather than an organ that was intended for transplantation (transplantation not done).

Thanks for the suggestion about the order. I will insert the field after the organ_part.

2024-03-12 04:52 UTC, hannes-ucsc commented on json_schema/type/biomaterial/specimen_from_organism.json
> +        "organ_donor": {
I see what you mean. I worry, though, that `organ_donor` will be misinterpreted to mean that the organism the specimen was taken from is an organ donor in general. There is also a potential "collision" of terms in that the donor schema is called donor_organism. I would stay away from "donor" altogether and use a term derived from "transplant". The description field is helpful but is not always available when users look at the metadata downstream, like in a JSON or TSV manifest generated by Azul.

Since this ultimately represents information about a process, i.e., *how* the specimen was collected, should this maybe be a field of the [collection_protocol](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/type/protocol/biomaterial_collection/collection_protocol.json) entity?

2024-03-12 11:00 UTC, arschat commented on json_schema/type/biomaterial/specimen_from_organism.json
> +        "organ_donor": {
I see your point, about the word *donor*. In that perspective I would suggest `transplant_organ`. 

About moving to collection_protocol, this field does not describe how the specimen was collected (this can be described by [this](http://www.ebi.ac.uk/efo/EFO_0009124) ontology, in `collection_protocol.method.text`).
This is about how the specimen was treated after the extraction because it was proposed for transplant. Similar fields that describe the process after the collection that affects the quality of the sample exist in the specimen level, like `specimen_from_organism.state_of_specimen.postmortem_interval`.

2024-03-12 15:49 UTC, hannes-ucsc commented on json_schema/type/biomaterial/specimen_from_organism.json
> +        "organ_donor": {
I like `transplant_organ`.

2024-03-13 17:11 UTC, hannes-ucsc approved these changes

2024-03-18 10:11 UTC, amnonkhen approved these changes

2024-03-19 04:42 UTC, NoopDog approved these changes

2024-03-21 09:19 UTC, ESapenaVentura approved these changes
LGTM; Let me know if you need assistance solving the conflicts

2024-03-22 11:20 UTC, merged