Add medical_tests module to donor_organism. Fixes #1562
HumanCellAtlas/metadata-schema pull request #1563
Opened 2024-07-10 15:48 UTC by arschat

### Release notes

For `donor_organism` schema, add a `medical_tests` module that includes the following fields.
* PFT_method
* PFT_age
* PFT_time_point
* PFT_relative_time_point
* FEV1_predicted
* FEV1_preBD
* FEV1_postBD
* FEV1_preBD_predicted_percent
* FEV1_postBD_predicted_percent
* FVC_predicted
* FVC_preBD
* FVC_postBD
* FVC_preBD_predicted_percent
* FVC_postBD_predicted_percent
* FEV1_FVC_ratio_preBD
* FEV1_FVC_ratio_postBD
* FRC_abs
* FRC_predicted_percent
* RV
* RV_predicted_percent
* IC
* IC_predicted_percent
* DLCO
* DLCO_predicted_percent
* KCO
* KCO_predicted_percent 

### Reviews requested

- Need 5 Reviewers to approve because this is a **minor** update

2024-07-22 14:33 UTC, idazucchi commented on json_schema/module/biomaterial/medical_tests.json
> +            "pattern": "^((0[1-9]|[12][0-9]|3[01])[- \\.\\/](0[1-9]|1[0-2])[- \\.\\/](19|20)\\d\\d|not_applicable)$",
the format for the date here is different from all the other dates in the schema, do we want to swap it?

2024-07-26 12:39 UTC, ncalvanese1 approved these changes

2024-07-26 16:51 UTC, hannes-ucsc commented
I'll hold off until EBI folks approve.

2024-07-29 10:04 UTC, ESapenaVentura requested changes
I have some comments about the naming of the fields, some missing values in the update log (And versions.json) and the usage of the `$comment` keyword

2024-07-29 10:04 UTC, ESapenaVentura commented on json_schema/module/biomaterial/medical_tests.json
> +        "KCO": {
please use snake_case formatting for the field name (e.g. `kco`, `kco_predicted_percent`). I know for some gene symbols/acronyms can be a bit weird, but we use this convention and the proper capitalization can be used in user_friendly.

2024-07-30 15:38 UTC, amnonkhen approved these changes

2024-08-01 09:18 UTC, arschat commented
Attribute names should convey intent, so we changed the `$comment` field to `bionetwork`.
Most of these Tier 2 fields are bionetwork specific and may not be relevant for other bionetworks. The intent is to record the bionetwork that requested this field, so we could generate bionetwork tailored spreadsheets directly from the schema.

2024-08-05 10:45 UTC, amnonkhen approved these changes

2024-08-12 17:18 UTC, hannes-ucsc approved these changes

2024-08-12 18:46 UTC, NoopDog approved these changes

2024-08-13 11:10 UTC, merged