Extend atlas names
HumanCellAtlas/metadata-schema pull request #1584
Opened 2024-10-09 11:43 UTC by arschat

### Release notes

For `hca_bionetwork.json` schema:
- Extend the controlled vocabulary of atlas names in `hca_tissue_atlas`
#1583 

### Reviews requested

- Need 5 Reviewers to approve because this is a patch update

2024-10-09 13:39 UTC, ESapenaVentura approved these changes

2024-10-09 13:39 UTC, ESapenaVentura commented on json_schema/update_log.csv
> +module/project/hca_bionetwork,patch,Extend atlas names in hca_bionetwork,,
We should revisit what minor/patch versions are like. Thanks for following the guide https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/evolution.md#schema-versioning but I think extending an enumeration should be considered a minor patch, as in my opinion any change in the schema that involves change in the validation rules should be at least a minor change. Anyways, this is good to go as per our specs! 🥇

2024-10-09 17:12 UTC, NoopDog requested changes
We can remove Eye-Other for now

2024-10-09 17:12 UTC, NoopDog commented on json_schema/module/project/hca_bionetwork.json
> +                "Eye - Other",
You can remove "Eye - Other"; this will be refined as the atlas becomes more focused.

2024-10-10 09:04 UTC, arschat commented on json_schema/module/project/hca_bionetwork.json
> +                "Eye - Other",
Thank you, Dave! Done.

2024-10-10 13:05 UTC, amnonkhen approved these changes

2024-10-10 18:31 UTC, hannes-ucsc approved these changes

2024-10-11 16:29 UTC, NoopDog approved these changes

2024-10-14 09:14 UTC, merged