Added enzymatic tissue dissociation fields
HumanCellAtlas/metadata-schema pull request #1599
Opened 2024-12-20 10:50 UTC by arschat

#1592 

### Release notes

For `dissociation_protocol.json` schema:
- rename `reagents` friendly name:
- add `digestion_time`
- add `digesion_time_units`
- add `digestion_temperature`
- add `digestion_solution` 

### Reviews requested

- Need 5 Reviewers to approve because this is a <minor> update

2024-12-20 15:52 UTC, ESapenaVentura requested changes
Minor comments and a change to the regex, otherwise LGTM!

2024-12-20 15:52 UTC, ESapenaVentura commented on json_schema/type/protocol/biomaterial_collection/dissociation_protocol.json
> +            "pattern": "\\d+(\\.\\d+)?|frozen|cold|room temperature|warm",
Pattern must be anchored (And it should be grouped in order to properly capture alternative groups):
```suggestion
            "pattern": "^(\\d+(\\.\\d+)?|frozen|cold|room temperature|warm)$",
```

2024-12-20 15:52 UTC, ESapenaVentura commented on json_schema/type/protocol/biomaterial_collection/dissociation_protocol.json
> +            "pattern": "\\d+(\\.\\d+)?|frozen|cold|room temperature|warm",
Otherwise, things like "11frozen", "frozencold" will be accepted https://regex101.com/r/iRzCpr/1

2024-12-20 15:52 UTC, ESapenaVentura commented on json_schema/update_log.csv
> +type/protocol/biomaterial_collection/dissociation_protocol,minor,Changed of user_friendly name of reagent field,,
```suggestion
type/protocol/biomaterial_collection/dissociation_protocol,minor,Changed user_friendly name of reagent field,,
```

very very minor correction :)

2025-01-07 16:16 UTC, ESapenaVentura approved these changes
LGTM 👍

2025-01-07 17:12 UTC, hannes-ucsc commented on json_schema/type/protocol/biomaterial_collection/dissociation_protocol.json
> +            "pattern": "^(\\d+(\\.\\d+)?|frozen|cold|room temperature|warm)$",
The number pattern matches non-sensical strings such as 00000000021.210000000000. Consider a union (`anyOf`) of `number` and `enum`. 

Then again, instead of allowing the subjective English terms, you could just allow for a range. That might be more elegant and easier to process for consumers.

2025-01-08 12:35 UTC, arschat commented on json_schema/type/protocol/biomaterial_collection/dissociation_protocol.json
> +            "pattern": "^(\\d+(\\.\\d+)?|frozen|cold|room temperature|warm)$",
Thank you for your comment, I agree on using range instead of words however, the Lung bionetwork insisted on using words to record this, as they used in the published version 1 of their atlas.

I've added the solution with the union of types in 0944f6e8822792c178664b558de41afd2e651677 .

2025-01-08 12:35 UTC, arschat commented on json_schema/type/protocol/biomaterial_collection/dissociation_protocol.json
> +                        ]
Thanks for pointing that out, fixed in 0944f6e8822792c178664b558de41afd2e651677

2025-01-08 18:50 UTC, hannes-ucsc approved these changes

2025-01-08 18:50 UTC, hannes-ucsc commented on json_schema/type/protocol/biomaterial_collection/dissociation_protocol.json
> +            "anyOf": [
I was confused but 

```suggestion
            "oneOf": [
```

is semantically equivalent (given that the alternatives are disjunctive) and adds clarity.

2025-01-09 20:11 UTC, NoopDog approved these changes

2025-01-14 13:33 UTC, ESapenaVentura approved these changes
LGTM!

2025-01-14 13:52 UTC, ncalvanese1 approved these changes

2025-01-21 15:59 UTC, amnonkhen approved these changes

2025-01-21 17:04 UTC, merged